# Generated by Django 4.2.9 on 2024-02-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_accountspayable_vendor'),
        ('inventory', '0004_inventorydetails_vendor_remove_inventory_vendor_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorcontact',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorContact',
        ),
    ]
