# Generated by Django 4.2.9 on 2024-08-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_retailinvoices_amount_paid_retailinvoices_date_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('internal_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Part Number')),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost')),
                ('qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinvoices')),
            ],
        ),
    ]
