# Generated by Django 4.2.9 on 2024-08-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_alter_retailinvoiceitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinvoiceitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor'),
        ),
    ]
