# Generated by Django 4.2.9 on 2024-08-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_rename_retailitemdetail_retailvendoritemdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinventorymaster',
            name='primary_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor'),
        ),
    ]
