# Generated by Django 4.2.9 on 2024-08-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_retailinventorymaster_primary_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinventorymaster',
            name='primary_vendor_part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Vendor Part Number'),
        ),
    ]
