# Generated by Django 4.2.9 on 2024-08-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0016_alter_retailinvoices_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailinvoiceitem',
            name='name',
        ),
        migrations.AddField(
            model_name='retailinvoiceitem',
            name='hr_name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
