# Generated by Django 4.2.9 on 2024-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_rename_hr_name_retailinvoiceitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='retailvendoritemdetail',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='High Price'),
        ),
    ]
