# Generated by Django 4.2.9 on 2024-07-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printleader', '0003_yourmodelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='PrintleaderSOORDEDT',
        ),
    ]
