# Generated by Django 4.2.9 on 2024-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printleader', '0005_printleadersoritl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Acctnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acctnum'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Act_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Act_time'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Attached',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Attached'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Blackink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Blackink'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Chgcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chgcode'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Commable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commable'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Costlabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costlabor'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Costpaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costpaper'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Cuts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuts'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Cutype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cutype'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Deptstot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deptstot'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Depttime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depttime'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Descript',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descript'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Diflev1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diflev1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Diflev2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diflev2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Discount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Discperc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discperc'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Done',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Extension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Fextension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fextension'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Forecast',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forecast'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Foreperc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreperc'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Fpercost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fpercost'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Fprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fprice'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Grain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grain'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Grain1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grain1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Hourly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hourly'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Hourly2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hourly2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Impres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Impres'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Inkside1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inkside1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Inkside2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inkside2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='InvoiceNum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='InvoiceNum'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Isparent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Isparent'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Item_Description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Itemlink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Itemlink'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Itemnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Itemnum'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Items',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Jnlbatch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jnlbatch'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Job_Category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Category'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Jobitem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jobitem'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Jobname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jobname'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Jobtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jobtype'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Labcost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Labcost'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Lineno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lineno'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Linetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linetype'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Margin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Margin'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Matcost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matcost'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Mouts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mouts'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Numoflots',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numoflots'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Numofons',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numofons'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Orddate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orddate'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Orditem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orditem'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Orgstat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orgstat'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Outs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outs'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overcop2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overcop2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overcopy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overcopy'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overhour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overhour'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overmanual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overmanual'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overperm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overperm'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Overs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overs'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Packprt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packprt'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pass1s',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pass1s'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pass2s',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pass2s'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Passink1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passink1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Passink2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passink2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Percost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Percost'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Plate12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plate12'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Platecost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platecost'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Platesale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platesale'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Plevel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plevel'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pplates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pplates'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Premium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Press',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Press2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Press_l',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press_l'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Press_w',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press_w'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Presstime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presstime'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pricem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pricem'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Proflabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proflabor'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Profpaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profpaper'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Profplate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profplate'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Prttable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prttable'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pss1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pss1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Pss2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pss2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty3'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty4'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty5'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Qty6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty6'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Salelabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salelabor'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Salepaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salepaper'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Setupt1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setupt1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Setupt2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setupt2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Sheets',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sheets'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Shpprt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shpprt'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Shpqty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shpqty'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Side12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Side12'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Sizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sizen'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Stock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Stockprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stockprice'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Stockqty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stockqty'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Taxable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxable'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Trimtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trimtype'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Unitpric2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitpric2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Unitprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitprice'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Units',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Usecuts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usecuts'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Useons',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Useons'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vendcostpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendcostpu'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vendmarkup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendmarkup'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vendponum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendponum'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vfl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vfl'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vfw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vfw'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vp'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vpl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vpl'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vppl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vppl'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Vpw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vpw'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Waste1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste1'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Waste2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste2'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Worktumb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Worktumb'),
        ),
        migrations.AlterField(
            model_name='printleaderarinvoda',
            name='Workturn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workturn'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Accessed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Accessed'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Acctnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acctnum'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Act_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Act_time'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Aftersub',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aftersub'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Attached',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Attached'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Backorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Backorder'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Blackink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Blackink'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Buildkit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buildkit'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Colordesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Colordesc'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Commable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Commable'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Cosacct',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cosacct'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Costlabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costlabor'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Costpaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costpaper'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Cpi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cpi'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Cuts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuts'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Cutype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cutype'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Deptstot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deptstot'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Depttime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depttime'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Descript',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descript'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Diflev1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diflev1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Diflev2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diflev2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Discamt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discamt'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Discount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Discperc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Discperc'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Done',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Dropship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dropship'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Emp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emp'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Explode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Explode'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Extension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Factor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factor'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Fdiscamt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fdiscamt'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Fextension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fextension'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Forecast',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forecast'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Foreperc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foreperc'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Fpercost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fpercost'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Fprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fprice'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Gpact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gpact'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Gpd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gpd'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Gpest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gpest'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Gpp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gpp'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Gpside',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gpside'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Grain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grain'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Grain1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grain1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Hourly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hourly'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Hourly2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hourly2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Impres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Impres'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Inkside1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inkside1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Inkside2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inkside2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Invacct',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invacct'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Isinvalid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Isinvalid'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Isparent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Isparent'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Isspeprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Isspeprice'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Item_Description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Itemlink',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Itemlink'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Itemnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Itemnum'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Items',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Job_Category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Category'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Jobitem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jobitem'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Jobtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jobtype'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Keyid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keyid'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Kitnum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kitnum'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Labcost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Labcost'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Linetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linetype'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Margin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Margin'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Matcost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matcost'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Mouts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mouts'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Numoflots',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numoflots'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Numofons',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numofons'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Oldstock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oldstock'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Orddate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orddate'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='OrderNum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OrderNum'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Orditem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orditem'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Orgstat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orgstat'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Outs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outs'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overcop2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overcop2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overcopy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overcopy'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overhou2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overhou2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overhour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overhour'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overmanual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overmanual'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overperm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overperm'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Overs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Overs'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Packprt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packprt'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pass1s',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pass1s'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pass2s',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pass2s'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Passink1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passink1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Passink2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Passink2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Percost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Percost'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Plate12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plate12'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Platecost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platecost'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Platesale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platesale'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Plevel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plevel'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pplates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pplates'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Premium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Premium'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Press',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Press2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Press_l',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press_l'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Press_w',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Press_w'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Presstime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Presstime'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pricechg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pricechg'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pricem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pricem'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Proflabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proflabor'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Profpaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profpaper'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Profplate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profplate'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Prttable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prttable'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pss1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pss1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Pss2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pss2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty3'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty4'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty5'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qty6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty6'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qtyback',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qtyback'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qtyord',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qtyord'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Qtyship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qtyship'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Quotn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quotn'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Salelabor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salelabor'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Salepaper',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salepaper'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Setmargin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setmargin'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Setupt1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setupt1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Setupt2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Setupt2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Sheets',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sheets'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Shpprt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shpprt'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Shpqty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shpqty'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Side12',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Side12'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Sizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sizen'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Sortdone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sortdone'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Spi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spi'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Stock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Stockpric2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stockpric2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Stockprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stockprice'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Stockqty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stockqty'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Taxable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxable'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Transfered',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transfered'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Trimtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trimtype'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Um',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Um'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Unitpric2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitpric2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Unitprice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitprice'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Units',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Units'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Usecuts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usecuts'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Useons',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Useons'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vendcostpu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendcostpu'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vendmarkup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendmarkup'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vendponum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendponum'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vfl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vfl'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vfw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vfw'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vp'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vpl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vpl'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vppl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vppl'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Vpw',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vpw'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Waste1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste1'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Waste2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waste2'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Whcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Whcode'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Worktumb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Worktumb'),
        ),
        migrations.AlterField(
            model_name='printleadersoordedt',
            name='Workturn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workturn'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Accessed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Accessed'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Bhc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bhc'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Costcent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Costcent'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Dact_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dact_time'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Done',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Done'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_amt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_amt'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_deptn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_deptn'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_desc'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_field'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_setup',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_setup'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_um',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_um'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_units',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_units'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='E_yn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E_yn'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Emp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emp'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Invoice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Itemtotal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Itemtotal'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Keyid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Keyid'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Ordersort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ordersort'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Orditem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orditem'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Prodhrs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prodhrs'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Ptime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ptime'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Schedule',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Sortdone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sortdone'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Stime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stime'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Taxitem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxitem'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Taxperc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxperc'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Unitcost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitcost'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Unitshr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unitshr'),
        ),
        migrations.AlterField(
            model_name='printleadersoritl',
            name='Workmess',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workmess'),
        ),
    ]
