# Generated by Django 4.2.9 on 2024-02-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('finance', '0001_initial'),
        ('workorders', '0028_fixedcost_material_markup_alter_fixedcost_duplo_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workorders.workorder'),
        ),
    ]
