# Generated by Django 4.2.9 on 2024-03-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0025_remove_workorderitem_test_user_and_more'),
        ('customers', '0008_customer_avg_days_to_pay_customer_credit_and_more'),
        ('finance', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(default=203, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workorders.workorder'),
        ),
    ]
