# Generated by Django 4.2.9 on 2024-03-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payments_customer_alter_payments_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='check_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Check Number'),
        ),
        migrations.AddField(
            model_name='payments',
            name='giftcard_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GiftCard Number'),
        ),
        migrations.AddField(
            model_name='payments',
            name='refunded_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Refund Invoice Number'),
        ),
    ]
