# Generated by Django 4.2.9 on 2024-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payments_check_number_payments_giftcard_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Memo'),
        ),
    ]
