# Generated by Django 4.2.9 on 2024-04-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payments_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountspayable',
            name='workorder',
        ),
    ]
