# Generated by Django 4.2.9 on 2024-04-05 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_avg_days_to_pay_customer_credit_and_more'),
        ('finance', '0008_araging_hr_customer_alter_araging_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliedother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('memo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Memo')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
        ),
    ]
