# Generated by Django 4.2.9 on 2024-04-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_appliedother'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='void',
            field=models.BooleanField(default=False, verbose_name='Void Payment'),
        ),
    ]
