# Generated by Django 4.2.9 on 2024-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payments_void'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountspayable',
            old_name='date_recieved',
            new_name='invoice_date',
        ),
    ]
