# Generated by Django 4.2.9 on 2024-05-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_date_recieved_accountspayable_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
