# Generated by Django 4.2.9 on 2024-06-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0048_alter_workorder_date_paid'),
        ('finance', '0013_payments_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Workorder', to='workorders.workorder'),
        ),
        migrations.CreateModel(
            name='WorkorderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Payment Amount')),
                ('date', models.DateField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payments')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='workorder_applied',
            field=models.ManyToManyField(through='finance.WorkorderPayment', to='workorders.workorder'),
        ),
    ]
