# Generated by Django 4.2.9 on 2024-08-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_accountspayable_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='invoice_number',
            field=models.CharField(blank=True, default='1', max_length=100, verbose_name='Invoice Number'),
            preserve_default=False,
        ),
    ]
