# Generated by Django 4.2.9 on 2024-08-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_accountspayable_retail_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount'),
        ),
    ]
