# Generated by Django 4.2.9 on 2024-08-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_vendoritemdetail'),
        ('finance', '0019_alter_accountspayable_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Unit Cost')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qty')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('internal_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.accountspayable')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
    ]
