# Generated by Django 4.2.9 on 2024-08-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='order_out',
            field=models.BooleanField(default=True, null=True, verbose_name='Order Out'),
        ),
    ]
