# Generated by Django 4.2.9 on 2024-08-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_accountspayable_order_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='variation_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Variation Qty'),
        ),
    ]
