# Generated by Django 4.2.9 on 2024-08-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_invoiceitem_variation_invoiceitem_variation_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='price_ea',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Price Each'),
        ),
    ]
