# Generated by Django 4.2.9 on 2024-08-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_inventoryqtyvariations_variation_qty'),
        ('finance', '0024_invoiceitem_price_ea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='variation_qty',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Invoice Qty'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_unit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Unit'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Invoice Unit Cost'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryqtyvariations'),
        ),
    ]
