# Generated by Django 4.2.9 on 2024-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_remove_invoiceitem_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='ppm',
            field=models.BooleanField(default=False, verbose_name='Price Per M'),
        ),
    ]
