# Generated by Django 4.2.9 on 2024-08-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_invoiceitem_ppm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price_ea',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Unit Cost'),
        ),
    ]
