# Generated by Django 4.2.9 on 2024-09-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_vendor_options_and_more'),
        ('finance', '0029_invoiceitem_line_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qty')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Unit Cost')),
                ('invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoiceitem')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
    ]
