# Generated by Django 4.2.9 on 2024-09-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_allinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinvoiceitem',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
