# Generated by Django 4.2.9 on 2024-09-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_allinvoiceitem_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinvoiceitem',
            name='invoice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
