# Generated by Django 4.2.9 on 2024-09-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_allinvoiceitem_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='calculated_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Calculated Total'),
        ),
        migrations.AlterField(
            model_name='allinvoiceitem',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoiceitem'),
        ),
    ]
