# Generated by Django 4.2.9 on 2024-09-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_accountspayable_calculated_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='non_inventory',
            field=models.BooleanField(default=True, null=True, verbose_name='Non Inventory Invoice'),
        ),
    ]
