# Generated by Django 4.2.9 on 2024-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_alter_accountspayable_order_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Unit Cost'),
        ),
    ]
