# Generated by Django 4.2.9 on 2024-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_alter_invoiceitem_invoice_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('ACH', 'ACH'), ('Trade', 'Trade'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Payment Method'),
        ),
    ]
