# Generated by Django 4.2.9 on 2024-09-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_vendor_options_and_more'),
        ('finance', '0038_alter_accountspayable_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinvoiceitem',
            name='internal_part_number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster'),
            preserve_default=False,
        ),
    ]
