# Generated by Django 4.2.9 on 2024-09-12 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0035_alter_groupcategory_name'),
        ('finance', '0039_allinvoiceitem_internal_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinvoiceitem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Line Total'),
        ),
        migrations.AddField(
            model_name='allinvoiceitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.measurement'),
        ),
    ]
