# Generated by Django 4.2.9 on 2024-09-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0041_allinvoiceitem_created_allinvoiceitem_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinvoiceitem',
            name='invoice_id',
        ),
    ]
