# Generated by Django 4.2.9 on 2024-09-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0042_alter_invoiceitem_internal_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='finance.accountspayable'),
        ),
        migrations.DeleteModel(
            name='AllInvoiceItem',
        ),
    ]
