# Generated by Django 4.2.9 on 2024-10-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_orderout_vendor'),
        ('finance', '0043_alter_invoiceitem_invoice_delete_allinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
