# Generated by Django 4.2.9 on 2025-07-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_accountspayable_check_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderpayment',
            name='date',
            field=models.DateField(),
        ),
    ]
