# Generated by Django 4.2.9 on 2025-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_krueger_araging'),
    ]

    operations = [
        migrations.AddField(
            model_name='araging',
            name='billed_today',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total open balance for invoices billed today', max_digits=10),
        ),
    ]
