# Generated by Django 4.2.9 on 2025-10-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0085_alter_orderout_options_and_more'),
        ('finance', '0047_krueger_araging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='internal_part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', related_query_name='invoice_item', to='inventory.inventorymaster'),
        ),
    ]
