# Generated by Django 4.2.9 on 2025-12-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_araging_billed_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='posted',
            field=models.BooleanField(default=False, help_text='If checked, this invoice is considered posted. Edits should be rare.'),
        ),
    ]
