# Generated by Django 4.2.9 on 2025-12-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0049_accountspayable_posted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payments',
            index=models.Index(fields=['customer', 'void', '-date'], name='pay_cust_void_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payments',
            index=models.Index(fields=['workorder', 'void', '-date'], name='pay_wo_void_date_idx'),
        ),
    ]
