# Generated by Django 4.2.9 on 2026-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_payments_pay_cust_void_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
