# Generated by Django 4.2.9 on 2026-01-30 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0057_workorder_wo_cust_list_idx_workorder_wo_ar_idx_and_more'),
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('finance', '0051_payments_refunded'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('memo_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('certificate_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('void', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderCreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('void', models.BooleanField(default=False)),
                ('credit_memo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.creditmemo')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCertificateRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('void', models.BooleanField(default=False)),
                ('gift_certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.giftcertificate')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
        migrations.AddIndex(
            model_name='giftcertificate',
            index=models.Index(fields=['customer', 'void', '-issued_date'], name='gc_cust_void_date_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcertificate',
            index=models.Index(fields=['certificate_number'], name='gc_number_idx'),
        ),
        migrations.AddIndex(
            model_name='creditmemo',
            index=models.Index(fields=['customer', 'void', '-date'], name='cm_cust_void_date_idx'),
        ),
    ]
