# Generated by Django 4.2.9 on 2026-02-10 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0052_creditmemo_giftcertificate_workordercreditmemo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditmemo',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditmemo',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditmemo',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_credit_memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_giftcerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payments',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
