# Generated by Django 4.2.9 on 2026-02-11 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0044_alter_paymenttype_detail_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0053_creditmemo_void_reason_creditmemo_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcerts_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcert_sales', to='controls.paymenttype'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='giftcertificate',
            index=models.Index(fields=['void', '-created_at'], name='gc_void_created_idx'),
        ),
    ]
