# Generated by Django 4.2.9 on 2026-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0054_giftcertificate_sold_at_giftcertificate_sold_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='certificate_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
