# Generated by Django 4.2.9 on 2026-02-11 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0019_retailsaleline_is_gift_certificate'),
        ('finance', '0055_alter_giftcertificate_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcertificate',
            name='sold_retail_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcerts_issued', to='retail.retailsale'),
        ),
    ]
