# Generated by Django 4.2.9 on 2026-02-11 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0057_creditadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpayment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderpayment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_workorder_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
