# Generated by Django 4.2.9 on 2026-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0058_workorderpayment_voided_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Qty'),
        ),
    ]
