# Generated by Django 4.2.9 on 2026-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0059_alter_invoiceitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
