# Generated by Django 4.2.9 on 2026-02-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0060_accountspayable_void_accountspayable_void_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Qty'),
        ),
    ]
