# Generated by Django 4.2.9 on 2026-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0061_alter_invoiceitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='ledger_locked',
            field=models.BooleanField(default=False, help_text='True once this line has written inventory movements to InventoryLedger. Prevents changing qty/unit/item/cost.'),
        ),
    ]
