# Generated by Django 4.2.9 on 2026-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0062_invoiceitem_ledger_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
