# Generated by Django 4.2.9 on 2026-04-01 20:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('finance', '0063_accountspayable_payment_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArSlowPayerSnapshotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('as_of_date', models.DateField(db_index=True)),
                ('status', models.CharField(db_index=True, default='running', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer_count', models.PositiveIntegerField(default=0)),
                ('closed_workorder_count', models.PositiveIntegerField(default=0)),
                ('avg_days_to_pay_overall', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('slow_payer_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArSlowPayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('closed_workorder_count', models.PositiveIntegerField(default=0)),
                ('avg_days_to_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_days_to_pay', models.IntegerField(blank=True, null=True)),
                ('max_days_to_pay', models.IntegerField(blank=True, null=True)),
                ('total_closed_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payer_band', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_slowpayer_snapshots', to='customers.customer')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.arslowpayersnapshotrun')),
            ],
            options={
                'ordering': ['-avg_days_to_pay', 'company_name'],
                'indexes': [models.Index(fields=['run', 'payer_band'], name='finance_ars_run_id_b088d7_idx'), models.Index(fields=['run', '-avg_days_to_pay'], name='finance_ars_run_id_d7edad_idx'), models.Index(fields=['customer', '-id'], name='finance_ars_custome_0bee3a_idx')],
            },
        ),
    ]
