# Generated by Django 4.2.9 on 2026-04-02 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('finance', '0064_arslowpayersnapshotrun_arslowpayersnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arslowpayersnapshot',
            options={'ordering': ['-avg_days_to_pay', '-score', 'company_name'], 'verbose_name': 'AR Slow Payer Snapshot', 'verbose_name_plural': 'AR Slow Payer Snapshots'},
        ),
        migrations.AlterModelOptions(
            name='arslowpayersnapshotrun',
            options={'ordering': ['-as_of_date', '-created_at'], 'verbose_name': 'AR Slow Payer Snapshot Run', 'verbose_name_plural': 'AR Slow Payer Snapshot Runs'},
        ),
        migrations.RemoveIndex(
            model_name='arslowpayersnapshot',
            name='finance_ars_run_id_d7edad_idx',
        ),
        migrations.RemoveIndex(
            model_name='arslowpayersnapshot',
            name='finance_ars_custome_0bee3a_idx',
        ),
        migrations.AddField(
            model_name='arslowpayersnapshot',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='arslowpayersnapshot',
            name='payer_band',
            field=models.CharField(choices=[('fast', 'Fast'), ('moderate', 'Moderate'), ('slow', 'Slow'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='arslowpayersnapshotrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='running', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='arslowpayersnapshot',
            unique_together={('run', 'customer')},
        ),
        migrations.AddIndex(
            model_name='arslowpayersnapshot',
            index=models.Index(fields=['run', 'avg_days_to_pay'], name='finance_ars_run_id_405785_idx'),
        ),
        migrations.AddIndex(
            model_name='arslowpayersnapshot',
            index=models.Index(fields=['run', 'score'], name='finance_ars_run_id_42373c_idx'),
        ),
        migrations.AddIndex(
            model_name='arslowpayersnapshot',
            index=models.Index(fields=['customer', 'created_at'], name='finance_ars_custome_9fb9d1_idx'),
        ),
    ]
