from django.contrib import admin
from django.urls import path
#from . import views

from .views import (
    create_base,
    overview,
    workorder_list,
    edit_workorder,
    workorder_info,
    history_overview,
    workorder_item_list,
    add_item,
    edit_modal_item,
    edit_print_item,
    remove_workorder_item,
    copy_workorder_item,
    copy_workorder,
    subcategory,
    tax,
    notes,
    workorder_notes,
    edit_design_item,
    edit_orderout_item,
    edit_set_price_item,
    quote_list,
    edit_custom_item,
    quote_to_workorder,
    readnotes,
    complete_status,
    billable_status,
    edit_parent_item,
    edit_postage_item,
    item_status,
    stale,
    abandon_quote,
    billed,
    task_notes,
    dashboard,
    workorder_k_list,
    workorder_lk_list,
    workorder_kos_list,
    void_workorder,
    void_status,
    close_pay_modal
    # removed,
)

app_name='workorders'

urlpatterns = [
    path('', create_base, name='createbase'),
    path('add/<int:parent_id>/', add_item, name='add_item'),
    path('items/<int:pk>/edit/<int:cat>', edit_modal_item, name='edit_modal_item'),
    path('design/<int:pk>/edit/<int:cat>', edit_design_item, name='edit_design_item'),
    path('custom/<int:pk>/edit/<int:cat>', edit_custom_item, name='edit_custom_item'),
    path('orderout/<int:pk>/edit/<int:cat>', edit_orderout_item, name='edit_orderout_item'),
    path('setprice/<int:pk>/edit/<int:cat>', edit_set_price_item, name='edit_set_price_item'),
    path('postage/<int:pk>/edit/<int:cat>', edit_postage_item, name='edit_postage_item'),
    path('parent/<int:pk>/workorder/<int:workorder>/edit/<int:cat>', edit_parent_item, name='edit_parent_item'),
    #path('items/<int:pk>/edit/<int:cat>', edit_print_item, name='edit_print_item'),
    path('items/<int:pk>/remove/', remove_workorder_item, name='remove_item'),
    path('items/copy_workorder/<int:id>', copy_workorder, name='copy_workorder'),
    path('items/<int:pk>/copy/', copy_workorder_item, name='copy_workorder_item'),
    path('items/<int:pk>/copy/<str:workorder>', copy_workorder_item, name='copy_workorder_item'),
    path("item/<int:id>/", workorder_item_list, name='workorder_item_list'),
    path("createbase/", create_base, name='createbase'), #Create base details of new workorder
    path("workorders/", workorder_list, name='workorder_list'),
    path("quotes/", quote_list, name='quote_list'),
    path("workorders/<int:id>", overview, name='overview'),
    path("workorders/<int:id>", history_overview, name='history_overview'),
    path("edit_workorder", edit_workorder, name='edit_workorder'),
    path("workorder_info/", workorder_info, name='workorder_info'),
    path("workorder_info/<int:workorder>/", workorder_info, name='workorder_info'),
    path('categories/', subcategory, name='subcategory'),
    path('tax/<str:tax>/<int:id>/', tax, name='tax'),
    path('task_notes/<int:pk>/<str:task>/', task_notes, name='task_notes'),
    path('notes/<int:pk>/', notes, name='notes'),
    path('item_status/<int:pk>/', item_status, name='item_status'),
    path('notes/', notes, name='notes'),
    path('stale/<int:pk>/', stale, name='stale'),
    path('readnotes/<int:pk>/', readnotes, name='readnotes'),
    path('workordernotes/<int:pk>/', workorder_notes, name='workorder_notes'),
    path('quote_to_workorder/', quote_to_workorder, name='quote_to_workorder'),
    path('complete_status/', complete_status, name='complete_status'),
    path('billable_status/<int:id>/', billable_status, name='billable_status'),
    path('abandon_quote/', abandon_quote, name='abandon_quote'),
    path('billed/<int:id>/', billed, name='billed'),
    path('dashboard/', dashboard, name='dashboard'),
    path("k_workorders/", workorder_k_list, name='workorder_k_list'),
    path("lk_workorders/", workorder_lk_list, name='workorder_lk_list'),
    path("kos_workorders/", workorder_kos_list, name='workorder_kos_list'),
    path("void_workorder/<int:pk>/<int:void>/", void_workorder, name='void_workorder'),
    path("void_workorder/", void_workorder, name='void_workorder'),
    path("void_status/", void_status, name='void_status'),
    path("close_modal/", close_pay_modal, name='close_pay_modal'),
    
    # path('removed/', removed, name='removed')
    

]