# Generated by Django 4.2.9 on 2024-02-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('design_type', models.BooleanField(blank=True, null=True, verbose_name='Design Type')),
                ('formname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form')),
                ('modelname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('modal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Popup Modal')),
                ('setprice', models.BooleanField(default=False, null=True, verbose_name='Is setprice category')),
                ('template', models.BooleanField(blank=True, default=False, null=True, verbose_name='Template')),
                ('customform', models.BooleanField(blank=True, default=False, null=True, verbose_name='Uses Custom Form')),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('create_workorder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Create Workordeer')),
                ('reclaim_artwork', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Reclaim Artwork')),
                ('send_to_press', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Send to press')),
                ('send_mailmerge_to_press', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Send Mailmerge to press')),
                ('material_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Material Markup Percentage')),
                ('wear_and_tear', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wear and Tear')),
                ('trim_to_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trim to Size')),
                ('duplo_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo1')),
                ('duplo_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo2')),
                ('duplo_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo3')),
                ('ncr_compound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NCR Compound')),
                ('pad_compound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Padding Compound')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='SetPriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('template', models.BooleanField(blank=True, default=False, null=True, verbose_name='Template')),
                ('set_price', models.BooleanField(default=False, null=True, verbose_name='Is setprice category')),
                ('setprice_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='controls.category')),
            ],
        ),
        migrations.CreateModel(
            name='SetPriceItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10, verbose_name='Quantity / Description')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Price')),
                ('name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='pricesheet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.fixedcost'),
        ),
    ]
