# Generated by Django 4.2.9 on 2024-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('create_workorder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Create Workordeer')),
                ('reclaim_artwork', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Reclaim Artwork')),
                ('send_to_press', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Send to press')),
                ('send_mailmerge_to_press', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Send Mailmerge to press')),
                ('material_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Material Markup Percentage')),
                ('wear_and_tear', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wear and Tear')),
                ('trim_to_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trim to Size')),
                ('duplo_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo1')),
                ('duplo_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo2')),
                ('duplo_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Duplo3')),
                ('ncr_compound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NCR Compound')),
                ('pad_compound', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Padding Compound')),
            ],
        ),
    ]
