# Generated by Django 4.2.9 on 2024-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_fixedcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('design_type', models.BooleanField(blank=True, null=True, verbose_name='Design Type')),
                ('formname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Form')),
                ('modelname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('modal', models.BooleanField(blank=True, default=False, null=True, verbose_name='Popup Modal')),
                ('setprice', models.BooleanField(default=False, null=True, verbose_name='Is setprice category')),
                ('template', models.BooleanField(blank=True, default=False, null=True, verbose_name='Template')),
                ('customform', models.BooleanField(blank=True, default=False, null=True, verbose_name='Uses Custom Form')),
                ('pricesheet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.fixedcost')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('template', models.BooleanField(blank=True, default=False, null=True, verbose_name='Template')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='controls.category')),
            ],
        ),
    ]
