# Generated by Django 4.2.9 on 2024-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_remove_setpriceitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setpriceitemprice',
            name='quantity',
        ),
        migrations.AddField(
            model_name='setpriceitemprice',
            name='set_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity / Order'),
        ),
    ]
