# Generated by Django 4.2.9 on 2024-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_remove_setpriceitemprice_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpriceitemprice',
            name='set_quantity',
            field=models.DecimalField(decimal_places=2, default='500', max_digits=10, verbose_name='Quantity / Order'),
            preserve_default=False,
        ),
    ]
