# Generated by Django 4.2.9 on 2024-02-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_measurement_setpriceitems_setprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetPriceItems',
            new_name='SetPriceItem',
        ),
        migrations.RenameModel(
            old_name='Setprices',
            new_name='SetPriceItemPrice',
        ),
    ]
