# Generated by Django 4.2.9 on 2024-02-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_alter_setpriceitemprice_set_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Type'),
        ),
        migrations.AlterField(
            model_name='setpriceitemprice',
            name='description',
            field=models.CharField(default='1', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
