# Generated by Django 4.2.9 on 2024-02-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_category_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpriceitemprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
