# Generated by Django 4.2.9 on 2024-03-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_alter_category_pricesheet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='wideformat',
            field=models.BooleanField(default=False, null=True, verbose_name='Wide Format'),
        ),
    ]
