# Generated by Django 4.2.9 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0013_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='icon',
            field=models.CharField(max_length=100, null=True, verbose_name='Icon'),
        ),
    ]
