# Generated by Django 4.2.9 on 2024-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0014_jobstatus_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobstatus',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='jobstatus/'),
        ),
    ]
