# Generated by Django 4.2.9 on 2024-03-14 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0019_jobstatus_workorder_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpriceitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setpriceitem',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
