# Generated by Django 4.2.9 on 2024-03-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0021_subcategory_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setpriceitem',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
