# Generated by Django 4.2.9 on 2024-03-18 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0022_alter_setpriceitem_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpriceitemprice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setpriceitemprice',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
