# Generated by Django 4.2.9 on 2024-03-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0031_alter_workorderitem_workorder'),
        ('controls', '0023_setpriceitemprice_created_setpriceitemprice_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetPriceItem',
            new_name='SetPriceCategory',
        ),
    ]
