# Generated by Django 4.2.9 on 2024-06-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0026_retailcategory_retailinventorycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinventorycategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='retail_category'),
        ),
        migrations.CreateModel(
            name='RetailInventorySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='retail_category')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('inventory_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.retailinventorycategory')),
            ],
        ),
    ]
