# Generated by Django 4.2.9 on 2024-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0028_retailinventorycategory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailsubcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='retailsubcategory',
            name='inventory_category',
        ),
        migrations.AddField(
            model_name='retailinventorycategory',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='retailinventorysubcategory',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
        migrations.DeleteModel(
            name='RetailCategory',
        ),
        migrations.DeleteModel(
            name='RetailSubCategory',
        ),
    ]
