# Generated by Django 4.2.9 on 2024-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0029_remove_retailsubcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinventorycategory',
            name='parent',
            field=models.CharField(max_length=10, null=True, verbose_name='Parent Category'),
        ),
    ]
