# Generated by Django 4.2.9 on 2024-07-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0032_alter_printleaderhistory_invoice_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrintleaderHistory',
        ),
    ]
