# Generated by Django 4.2.9 on 2024-09-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_inventorymaster_grouped_inventorymaster_price_group_and_more'),
        ('controls', '0034_groupcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupCategory',
        ),
    ]
