# Generated by Django 4.2.9 on 2024-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0035_alter_groupcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Test'),
        ),
    ]
