# Generated by Django 4.2.9 on 2025-09-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0036_alter_groupcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
