# Generated by Django 4.2.9 on 2025-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0037_alter_groupcategory_name'),
    ]

    operations = []  # No-op: table already created in 0034
