# Generated by Django 4.2.9 on 2025-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0038_create_groupcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
