# Generated by Django 4.2.9 on 2025-09-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0039_alter_groupcategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='designtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='fixedcost',
            options={'ordering': ('name',), 'verbose_name_plural': 'Fixed costs'},
        ),
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='numbering',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='postagetype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='retailinventorycategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='retailinventorysubcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='setpricecategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='setpriceitemprice',
            options={'ordering': ('description',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='create_workorder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Create Workorder'),
        ),
    ]
