# Generated by Django 4.2.9 on 2025-11-19 21:51

from django.db import migrations

def create_retailitem_category(apps, schema_editor):
    Category = apps.get_model("controls", "Category")

    Category.objects.get_or_create(
        name="RetailItem",
        defaults={
            "description": "Retail POS line items",
            "design_type": False,
            "formname": "",
            "modelname": "",
            "modal": False,
            "setprice": False,          # or True if you want it in SetPrice flows
            "material_type": "",
            "template": False,
            "customform": False,
            "pricesheet_type": None,
            "inventory_category": None,
            "wideformat": False,
            "active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0040_seed_jobstatus'),
    ]

    operations = [
        migrations.RunPython(create_retailitem_category, migrations.RunPython.noop),
    ]
