# Generated by Django 4.2.9 on 2025-09-22 19:20

from django.db import migrations, models
from django.db.models import Count

def dedupe_setpricecategory(apps, schema_editor):
    SetPriceCategory = apps.get_model('controls', 'SetPriceCategory')
    SetPriceItemPrice = apps.get_model('controls', 'SetPriceItemPrice')

    # Find groups with duplicates by (category_id, name)
    dup_groups = (
        SetPriceCategory.objects
        .values('category_id', 'name')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )

    for g in dup_groups:
        # deterministically keep the lowest id, merge the rest into it
        dups = list(
            SetPriceCategory.objects
            .filter(category_id=g['category_id'], name=g['name'])
            .order_by('id')
        )
        keeper = dups[0]
        for extra in dups[1:]:
            # Re-point any child rows that FK to the duplicate category
            # SetPriceItemPrice.name -> FK to SetPriceCategory
            SetPriceItemPrice.objects.filter(name_id=extra.id).update(name_id=keeper.id)
            # Now delete the duplicate row
            extra.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0040_alter_category_options_alter_designtype_options_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_setpricecategory, migrations.RunPython.noop),

        migrations.AlterModelOptions(
            name='setpricecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.AddConstraint(
            model_name='setpricecategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_setpricecategory_per_category'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_subcategory_per_category'),
        ),
    ]
