# Generated by Django 4.2.9 on 2025-11-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_add_retailitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinventorycategory',
            name='default_markup_flat',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Flat dollars added over cost for this category.', max_digits=15, null=True, verbose_name='Default Markup $'),
        ),
        migrations.AddField(
            model_name='retailinventorycategory',
            name='default_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent over cost for items in this category.', max_digits=5, null=True, verbose_name='Default Markup %'),
        ),
    ]
