# Generated by Django 4.2.9 on 2025-10-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_alter_setpricecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
