# Generated by Django 4.2.9 on 2025-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0098_alter_inventorypricinggroup_inventory'),
        ('controls', '0042_measurement_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='controls.groupcategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='inventory.inventorymaster')),
            ],
            options={
                'unique_together': {('category', 'item')},
            },
        ),
    ]
