# Generated by Django 4.2.9 on 2025-12-03 15:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0042_retailinventorycategory_default_markup_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinventorycategory',
            name='default_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), help_text='Percent over cost for items in this category.', max_digits=5, null=True, verbose_name='Default Markup %'),
        ),
        migrations.AlterField(
            model_name='retailinventorycategory',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
    ]
