# Generated by Django 4.2.9 on 2026-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0043_alter_retailinventorycategory_default_markup_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='detail_field',
            field=models.CharField(blank=True, help_text='Leave blank unless this payment type requires extra info (check #, gift card #, etc.)', max_length=100, null=True, verbose_name='Detail Field'),
        ),
    ]
