# Generated by Django 4.2.9 on 2026-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0044_alter_paymenttype_detail_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
