# Generated by Django 4.2.9 on 2024-08-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0033_delete_printleaderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBreaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('qty_full_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full Price Qty')),
                ('full_price_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Full Price Pct')),
                ('qty_break_one', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Break 1 Qty')),
                ('break_one_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Break 1 Pct')),
                ('qty_break_two', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Break 2 Qty')),
                ('break_two_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Break 2 Pct')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('internal_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Part Number')),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost')),
                ('current_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('retail_item', models.BooleanField(default=True, verbose_name='Retail Item')),
                ('inventory_category', models.ManyToManyField(to='controls.retailinventorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('primary_vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Vendor Part Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='High Price')),
            ],
        ),
        migrations.CreateModel(
            name='RetailVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('supplier', models.BooleanField(default=True, verbose_name='Supplier')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailVendorItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='High Price')),
                ('internal_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('vendor_item_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('shipped_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('internal_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('price_per_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock Price per M')),
                ('total_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Price')),
                ('internal_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.measurement')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailinventory')),
                ('shipped_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_shipped_uom', to='controls.measurement')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total')),
                ('date_due', models.DateField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('discount_date_due', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False, null=True, verbose_name='Paid')),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('Trade', 'Trade'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Payment Method')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Unit Cost')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qty')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('internal_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinvoices')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
        migrations.AddField(
            model_name='retailinventorymaster',
            name='primary_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor'),
        ),
        migrations.CreateModel(
            name='RetailInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('qty_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qty on Hand')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inventory_category', models.ManyToManyField(to='controls.retailinventorycategory')),
                ('office_supply_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.officesupplies')),
                ('paper_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinventory')),
            ],
        ),
    ]
