# Generated by Django 4.2.9 on 2024-08-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_alter_retailinvoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailvendoritemdetail',
            name='internal_part_number',
        ),
        migrations.AddField(
            model_name='retailvendoritemdetail',
            name='internal_part_number',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster'),
            preserve_default=False,
        ),
    ]
