# Generated by Django 4.2.9 on 2024-08-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_remove_retailvendoritemdetail_internal_part_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceBreaks',
        ),
        migrations.RemoveField(
            model_name='retailinventory',
            name='inventory_category',
        ),
        migrations.RemoveField(
            model_name='retailinventorydetail',
            name='inventory_category',
        ),
        migrations.RemoveField(
            model_name='retailinventorydetail',
            name='office_supply_item',
        ),
        migrations.RemoveField(
            model_name='retailinventorydetail',
            name='paper_item',
        ),
        migrations.RemoveField(
            model_name='retailpurchasehistory',
            name='internal_uom',
        ),
        migrations.RemoveField(
            model_name='retailpurchasehistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='retailpurchasehistory',
            name='shipped_uom',
        ),
        migrations.RemoveField(
            model_name='retailpurchasehistory',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='OfficeSupplies',
        ),
        migrations.DeleteModel(
            name='RetailInventory',
        ),
        migrations.DeleteModel(
            name='RetailInventoryDetail',
        ),
        migrations.DeleteModel(
            name='RetailPurchaseHistory',
        ),
    ]
