# Generated by Django 4.2.9 on 2024-08-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_vendor_retail_vendor'),
        ('retail', '0005_delete_pricebreaks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='retailinvoices',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='retailvendoritemdetail',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
