# Generated by Django 4.2.9 on 2026-03-17 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('workorders', '0058_alter_workorderitem_options_workorderitem_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAssetOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_item_id', models.CharField(db_index=True, max_length=36)),
                ('archive_filename', models.CharField(blank=True, default='', max_length=500)),
                ('archive_path', models.TextField(blank=True, default='')),
                ('archive_hash', models.CharField(blank=True, default='', max_length=64)),
                ('asset_role', models.CharField(choices=[('reference', 'Reference'), ('source', 'Source'), ('proof', 'Proof'), ('print_ready', 'Print Ready'), ('other', 'Other')], default='reference', max_length=30)),
                ('print_ready', models.BooleanField(default=False)),
                ('official_asset', models.BooleanField(default=False)),
                ('reuse_approved', models.BooleanField(default=False)),
                ('do_not_use', models.BooleanField(default=False)),
                ('notes_summary', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_archive_overlays', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_assets', to='customers.customer')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_assets', to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveAssetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='archive_overlay.archiveassetoverlay')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveAssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='archive_overlay.archiveassetoverlay')),
            ],
            options={
                'unique_together': {('overlay', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='archiveassetoverlay',
            index=models.Index(fields=['archive_item_id'], name='archive_ove_archive_4f5902_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveassetoverlay',
            index=models.Index(fields=['customer', 'workorder'], name='archive_ove_custome_7abca5_idx'),
        ),
    ]
