# Generated by Django 4.2.9 on 2024-03-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_status',
        ),
    ]
