# Generated by Django 4.2.9 on 2024-02-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorders', '0028_fixedcost_material_markup_alter_fixedcost_duplo_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('internal_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Part Number')),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost')),
                ('current_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
                ('measurement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Measurement')),
                ('type_paper', models.BooleanField(default=False, verbose_name='Paper')),
                ('type_envelope', models.BooleanField(default=False, verbose_name='Envelope')),
                ('type_wideformat', models.BooleanField(default=False, verbose_name='Wide Format')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.category')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_item_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('inventorydetails', models.ManyToManyField(through='inventory.InventoryDetail', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor'),
        ),
    ]
