# Generated by Django 4.2.9 on 2024-02-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='test',
            field=models.CharField(blank=True, max_length=100, verbose_name='test'),
        ),
    ]
