# Generated by Django 4.2.9 on 2024-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetails',
            name='vendor_item_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number'),
        ),
    ]
