# Generated by Django 4.2.9 on 2024-02-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setprice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='setprice',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='setprice',
            name='setprice_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='setprice_item',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Category'),
        ),
    ]
