# Generated by Django 4.2.9 on 2024-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorydetails_vendor_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type_envelope',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='type_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='type_wideformat',
            field=models.BooleanField(default=False),
        ),
    ]
