# Generated by Django 4.2.9 on 2024-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_setprice_category_remove_setprice_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprice',
            name='setprice_category',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='setprice',
            name='setprice_item',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Item'),
        ),
    ]
