# Generated by Django 4.2.9 on 2024-02-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_measurement_alter_inventory_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price_per_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock Price per M'),
        ),
    ]
