# Generated by Django 4.2.9 on 2024-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_setprice_setprice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setprice',
            name='setprice_qty',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pieces / set'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='total_pieces',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Total pieces'),
        ),
    ]
