# Generated by Django 4.2.9 on 2024-02-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_setprice_setprice_qty_setprice_total_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='setprice',
            name='setprice_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Price / set'),
        ),
    ]
