# Generated by Django 4.2.9 on 2024-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_setprice_setprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprice',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
    ]
