# Generated by Django 4.2.9 on 2024-02-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0033_remove_workorderitem_percent_markup_and_more'),
        ('customers', '0010_customer_customer_number_alter_customer_tax_exempt'),
        ('inventory', '0005_remove_inventory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('hr_workorder', models.CharField(max_length=100, verbose_name='Human Readable Workorder')),
                ('workorder_item', models.CharField(max_length=100, verbose_name='Workorder Item')),
                ('category', models.CharField(blank=True, max_length=10, null=True, verbose_name='Category')),
                ('hr_customer', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Purchase Price')),
                ('percent_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Percent Markup')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Price')),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Override Price')),
                ('last_item_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order')),
                ('last_item_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes:')),
                ('dateentered', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False, verbose_name='Billed')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited')),
                ('customer', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.vendor')),
                ('workorder', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
    ]
