# Generated by Django 4.2.9 on 2024-02-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_customer_number_alter_customer_tax_exempt'),
        ('workorders', '0034_category_modelname_alter_category_modal'),
        ('inventory', '0006_orderout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='hr_customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='hr_workorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Human Readable Workorder'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='workorder_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Workorder Item'),
        ),
        migrations.CreateModel(
            name='SetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_workorder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Human Readable Workorder')),
                ('workorder_item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Workorder Item')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('hr_customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('category', models.CharField(blank=True, max_length=10, null=True, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('customer', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer')),
                ('workorder', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
    ]
