# Generated by Django 4.2.9 on 2024-02-10 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_orderout_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setprice',
            name='billed',
            field=models.BooleanField(default=False, verbose_name='Billed'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='dateentered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setprice',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='last_item_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='last_item_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes:'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Override Price'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
