# Generated by Django 4.2.9 on 2024-02-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_setprice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='setprice',
            name='paper_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='setprice',
            name='side_1_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], default='None', max_length=100, verbose_name='Side 1 Ink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setprice',
            name='side_2_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], default='None', max_length=100, verbose_name='Side 1 Ink'),
            preserve_default=False,
        ),
    ]
