# Generated by Django 4.2.9 on 2024-02-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_setprice_paper_stock_setprice_side_1_inktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprice',
            name='side_1_inktype',
            field=models.CharField(blank=True, choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, null=True, verbose_name='Side 1 Ink'),
        ),
        migrations.AlterField(
            model_name='setprice',
            name='side_2_inktype',
            field=models.CharField(blank=True, choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, null=True, verbose_name='Side 1 Ink'),
        ),
    ]
