# Generated by Django 4.2.9 on 2024-02-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_setprice_subcategory_photography'),
    ]

    operations = [
        migrations.AddField(
            model_name='setprice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Setprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Category')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='Category')),
                ('name', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.setprice')),
            ],
        ),
    ]
