# Generated by Django 4.2.9 on 2024-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0008_inventorycategory_category_inventory_category'),
        ('inventory', '0010_inventorycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_category',
            field=models.ManyToManyField(to='controls.inventorycategory'),
        ),
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
    ]
