# Generated by Django 4.2.9 on 2024-02-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_setprice_name_setprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPriceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='setprices',
            name='name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.setpriceitems'),
        ),
    ]
