# Generated by Django 4.2.9 on 2024-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_setpriceitems_alter_setprices_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprices',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='setprices',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Quantity'),
        ),
    ]
