# Generated by Django 4.2.9 on 2024-02-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_category_subcategory'),
        ('inventory', '0012_alter_setprices_price_alter_setprices_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprice',
            name='subcategory',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.subcategory'),
        ),
    ]
