# Generated by Django 4.2.9 on 2024-02-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_setprice_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setprices',
            name='name',
        ),
        migrations.DeleteModel(
            name='SetPriceItems',
        ),
        migrations.DeleteModel(
            name='Setprices',
        ),
    ]
