# Generated by Django 4.2.9 on 2024-03-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_alter_workorder_customer_and_more'),
        ('inventory', '0013_alter_vendor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorydetail',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='inventorydetail',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='setprice',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
