# Generated by Django 4.2.9 on 2024-02-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_rename_setpriceitems_setpriceitem_and_more'),
        ('inventory', '0014_remove_setprices_name_delete_setpriceitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.measurement'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
