# Generated by Django 4.2.9 on 2024-03-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_category_wideformat'),
        ('inventory', '0016_remove_inventory_height_inventory_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='length_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='length_mea', to='controls.measurement'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='width_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='width_mea', to='controls.measurement'),
        ),
    ]
