# Generated by Django 4.2.9 on 2024-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventory_type_laminate_inventory_type_substrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='type_vinyl',
            field=models.BooleanField(default=False, verbose_name='Vinyl'),
        ),
    ]
