# Generated by Django 4.2.9 on 2024-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_inventory_type_vinyl'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price_per_sqft',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price per SqFt'),
        ),
    ]
