# Generated by Django 4.2.9 on 2024-03-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0031_alter_workorderitem_workorder'),
        ('inventory', '0021_inventory_price_per_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='setprice',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
    ]
