# Generated by Django 4.2.9 on 2024-04-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0024_rename_setpriceitem_setpricecategory'),
        ('inventory', '0023_remove_inventorydetail_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='internal_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='internal_uom', to='controls.measurement'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='shipped_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipped_uom', to='controls.measurement'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='total_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Price'),
        ),
    ]
