# Generated by Django 4.2.9 on 2024-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventorydetail_internal_uom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetail',
            old_name='qty',
            new_name='internal_qty',
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='shipped_qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty'),
        ),
    ]
