# Generated by Django 4.2.9 on 2024-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_rename_qty_inventorydetail_internal_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprice',
            name='side_2_inktype',
            field=models.CharField(blank=True, choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, null=True, verbose_name='Side 2 Ink'),
        ),
    ]
