# Generated by Django 4.2.9 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_orderout_percent_markup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='setprice',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
    ]
