# Generated by Django 4.2.9 on 2024-04-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_orderout_internal_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='supplier',
            field=models.BooleanField(default=True, verbose_name='Supplier'),
        ),
    ]
