# Generated by Django 4.2.9 on 2024-06-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_vendor_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='retail_item',
            field=models.BooleanField(default=True, verbose_name='Retail Item'),
        ),
    ]
