# Generated by Django 4.2.9 on 2024-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_inventory_retail_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock')),
            ],
        ),
    ]
