# Generated by Django 4.2.9 on 2024-08-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='retail_vendor',
            field=models.BooleanField(default=True, verbose_name='Retail Vendor'),
        ),
    ]
