# Generated by Django 4.2.9 on 2024-08-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_vendoritemdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='internal_part_number',
            new_name='vendor_part_number',
        ),
    ]
