# Generated by Django 4.2.9 on 2024-08-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_rename_internal_part_number_inventory_vendor_part_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='inventorydetails',
        ),
        migrations.DeleteModel(
            name='InventoryDetail',
        ),
    ]
