# Generated by Django 4.2.9 on 2024-08-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_vendor_inventorydetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='internal_part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='vendor_part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number'),
        ),
    ]
