# Generated by Django 4.2.9 on 2024-08-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0033_delete_printleaderhistory'),
        ('inventory', '0039_inventory_internal_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.measurement'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='price_per_m',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock Price per M'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='price_per_sqft',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Price per SqFt'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='unit_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='units_per_package',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Units per package'),
        ),
    ]
