# Generated by Django 4.2.9 on 2024-08-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_remove_inventorymaster_price_per_sqft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPricingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQtyVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryQtyVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itemqtyvariations')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPricingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.itempricinggroup')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster')),
            ],
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='pricing_group',
            field=models.ManyToManyField(through='inventory.InventoryPricingGroup', to='inventory.itempricinggroup'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='qty_variations',
            field=models.ManyToManyField(through='inventory.InventoryQtyVariations', to='inventory.itemqtyvariations'),
        ),
    ]
