# Generated by Django 4.2.9 on 2024-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_itempricinggroup_itemqtyvariations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypricinggroup',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='High Price'),
        ),
    ]
