# Generated by Django 4.2.9 on 2024-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_itemqtyvariations_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryqtyvariations',
            name='variation_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Variation Qty'),
        ),
    ]
