# Generated by Django 4.2.9 on 2024-09-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0033_delete_printleaderhistory'),
        ('inventory', '0046_remove_inventorymaster_measurement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='qty_variations',
        ),
        migrations.AlterField(
            model_name='inventoryqtyvariations',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.measurement'),
        ),
        migrations.DeleteModel(
            name='ItemQtyVariations',
        ),
    ]
