# Generated by Django 4.2.9 on 2024-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_remove_inventorymaster_qty_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='units_per_package',
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='units_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Units per base unit'),
        ),
    ]
