# Generated by Django 4.2.9 on 2024-09-04 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_inventorymaster_grouped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymaster',
            old_name='grouped',
            new_name='not_grouped',
        ),
    ]
