# Generated by Django 4.2.9 on 2024-09-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_alter_inventorymaster_not_grouped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='not_grouped',
        ),
    ]
