# Generated by Django 4.2.9 on 2024-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0034_groupcategory'),
        ('inventory', '0054_inventorymaster_not_grouped'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='grouped',
            field=models.BooleanField(default=False, verbose_name='In price group'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='price_group',
            field=models.ManyToManyField(to='controls.groupcategory'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='units_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Units per base unit (almost always 1)'),
        ),
    ]
