# Generated by Django 4.2.9 on 2024-09-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0035_pricegroupcategory_delete_groupcategory'),
        ('inventory', '0055_inventorymaster_grouped_inventorymaster_price_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='inventorymaster',
            name='pricing_group',
        ),
        migrations.AddField(
            model_name='vendor',
            name='inventory_vendor',
            field=models.BooleanField(default=True, verbose_name='Inventory Vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='non_inventory_vendor',
            field=models.BooleanField(default=True, verbose_name='Non Inventory Vendor'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='non_inventory',
            field=models.BooleanField(verbose_name='Non Inventory Item'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='price_group',
            field=models.ManyToManyField(blank=True, to='controls.pricegroupcategory'),
        ),
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.pricegroupcategory'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='non_inventory',
            field=models.BooleanField(verbose_name='Non Inventory Item'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='retail',
            field=models.BooleanField(verbose_name='Retail Item'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='supplies',
            field=models.BooleanField(verbose_name='Supply Item'),
        ),
    ]
