# Generated by Django 4.2.9 on 2024-09-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_alter_vendor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaster',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='High Price'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='units_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Units per base unit (almost always 1)'),
        ),
    ]
