# Generated by Django 4.2.9 on 2024-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_remove_inventorymaster_pricing_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='inventory_vendor',
            field=models.BooleanField(default=True, verbose_name='Retail Vendor'),
        ),
    ]
