# Generated by Django 4.2.9 on 2024-10-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_vendor_void'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor'),
        ),
    ]
