# Generated by Django 4.2.9 on 2024-10-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_alter_orderout_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='online_store',
            field=models.BooleanField(default=True, verbose_name='Online Store Item'),
        ),
    ]
