# Generated by Django 4.2.9 on 2024-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_inventorymaster_online_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='online_store_vendor',
            field=models.BooleanField(default=False, verbose_name='Online Store Vendor'),
        ),
    ]
