# Generated by Django 4.2.9 on 2024-10-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_vendor_online_store_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritemdetail',
            name='online_store',
            field=models.BooleanField(default=0, verbose_name='Online Store Item'),
            preserve_default=False,
        ),
    ]
