# Generated by Django 4.2.9 on 2024-11-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0062_vendoritemdetail_online_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.vendor'),
        ),
    ]
