# Generated by Django 4.2.9 on 2025-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_vendoritemdetail_vendor'),
        ('controls', '0037_alter_groupcategory_name'), # ensure GroupCategory exists
    ]

    operations = []  # No-op: the M2M table was created in 0055
