# Generated by Django 4.2.9 on 2025-11-04 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0064_add_inventorymaster_price_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InventoryMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_from', to='inventory.inventorymaster')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_into', to='inventory.inventorymaster')),
            ],
            options={
                'unique_together': {('from_item', 'to_item')},
            },
        ),
    ]
