# Generated by Django 4.2.9 on 2025-09-19 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_add_inventorymaster_price_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorcontact',
            options={'ordering': ('lname', 'fname')},
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='non_inventory',
            field=models.BooleanField(default=False, verbose_name='Non Inventory Item'),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='inventory.vendor'),
        ),
    ]
