# Generated by Django 4.2.9 on 2025-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('inventory', '0065_alter_vendorcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
