# Generated by Django 4.2.9 on 2025-11-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_retailsale_workorder'),
        ('workorders', '0053_workorder_retail_pos'),
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('inventory', '0065_inventorymaster_active_inventorymerge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailWorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], default='Office Supplies', max_length=100, verbose_name='Internal Company')),
                ('hr_customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Price')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('dateentered', models.DateTimeField(auto_now_add=True)),
                ('billed', models.BooleanField(default=False, verbose_name='Billed')),
                ('edited', models.BooleanField(default=False, verbose_name='Edited')),
                ('customer', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_items', to='retail.retailsale')),
                ('workorder', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_items', to='workorders.workorder')),
            ],
        ),
    ]
