# Generated by Django 4.2.9 on 2025-11-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_retailworkorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailworkorderitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_workorder_items', to='inventory.inventorymaster'),
        ),
    ]
