# Generated by Django 4.2.9 on 2025-09-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_alter_orderout_customer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorypricinggroup',
            index=models.Index(fields=['group'], name='inventory_i_group_i_7dc35a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryqtyvariations',
            index=models.Index(fields=['inventory'], name='inventory_i_invento_09af24_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryqtyvariations',
            index=models.Index(fields=['variation'], name='inventory_i_variati_f16486_idx'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['billed'], name='inventory_o_billed_85f584_idx'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['dateentered'], name='inventory_o_dateent_c58660_idx'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['vendor', 'dateentered'], name='inventory_o_vendor__5cfa94_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorypricinggroup',
            constraint=models.UniqueConstraint(fields=('inventory', 'group'), name='uniq_inventory_group'),
        ),
    ]
