# Generated by Django 4.2.9 on 2025-11-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_add_retailitem_category'),
        ('inventory', '0067_alter_retailworkorderitem_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaster',
            name='retail_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='controls.retailinventorycategory'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='retail_markup_flat',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Flat dollars added over cost.', max_digits=15, null=True, verbose_name='Retail Markup $'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='retail_markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent markup over unit cost (e.g. 50 = 50%).', max_digits=5, null=True, verbose_name='Retail Markup %'),
        ),
        migrations.AddField(
            model_name='inventorymaster',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Explicit retail price. If set, overrides markup rules.', max_digits=15, null=True, verbose_name='Retail Price'),
        ),
    ]
