# Generated by Django 4.2.9 on 2025-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_alter_vendor_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorypricinggroup',
            name='uniq_inventory_group',
        ),
        migrations.AddConstraint(
            model_name='inventorypricinggroup',
            constraint=models.UniqueConstraint(fields=('inventory', 'group'), name='uniq_inventory_group_once'),
        ),
    ]
