# Generated by Django 4.2.9 on 2025-12-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0068_inventorymaster_retail_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRetailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, help_text='Cost used as the basis for this retail price.', max_digits=15, null=True, verbose_name='Purchase Price')),
                ('calculated_price', models.DecimalField(blank=True, decimal_places=4, help_text='Price computed from unit cost + markup rules.', max_digits=15, null=True, verbose_name='Calculated Retail Price')),
                ('override_price', models.DecimalField(blank=True, decimal_places=4, help_text='If set, this is the default sell price for POS.', max_digits=15, null=True, verbose_name='Override Retail Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text="Optional note (e.g. 'manager override 12/1/25').", max_length=200)),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_pricing', to='inventory.inventorymaster')),
            ],
            options={
                'verbose_name': 'Inventory Retail Price',
                'verbose_name_plural': 'Inventory Retail Prices',
            },
        ),
    ]
