# Generated by Django 4.2.9 on 2025-09-22 21:07

from django.db import migrations, models
from django.db.models import Count, Max

def dedupe_vendoritemdetail(apps, schema_editor):
    VendorItemDetail = apps.get_model('inventory', 'VendorItemDetail')

    # Find all (internal_part_number, vendor) groups with > 1 rows
    dupes = (
        VendorItemDetail.objects
        .values('internal_part_number_id', 'vendor_id')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for key in dupes:
        qs = VendorItemDetail.objects.filter(
            internal_part_number_id=key['internal_part_number_id'],
            vendor_id=key['vendor_id'],
        ).order_by('-updated', '-id')  # newest wins

        keep = qs.first()

        # Optionally merge a better high_price if any row has it
        best_high = qs.aggregate(Max('high_price'))['high_price__max']
        if best_high is not None and (keep.high_price or 0) != best_high:
            keep.high_price = best_high
            keep.save(update_fields=['high_price'])

        # Delete all other duplicates
        qs.exclude(pk=keep.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_remove_inventorypricinggroup_uniq_inventory_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderout',
            options={'ordering': ['-dateentered']},
        ),
        migrations.AddField(
            model_name='orderout',
            name='open',
            field=models.BooleanField(default=True),
        ),

        migrations.AddConstraint(
            model_name='vendoritemdetail',
            constraint=models.UniqueConstraint(fields=('internal_part_number', 'vendor'), name='uq_vendor_detail_once_per_vendor'),
        ),
    ]
