# Generated by Django 4.2.9 on 2025-12-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_inventoryretailprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('qty_delta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('source_type', models.CharField(choices=[('AP_RECEIPT', 'AP Receipt / Invoice'), ('POS_SALE', 'POS Sale'), ('POS_REFUND', 'POS Refund'), ('WO_ORDEROUT', 'Workorder Item (OrderOut)'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='inventory.inventorymaster')),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
