# Generated by Django 4.2.9 on 2026-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_inventoryledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryqtyvariations',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional explicit retail price for this unit (e.g., dozen = 2.00). If blank, POS can compute from base price × multiplier.', max_digits=10, null=True),
        ),
    ]
