# Generated by Django 4.2.9 on 2026-02-13 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0072_units_and_guardrails'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryqtyvariations',
            new_name='inventory_i_invento_1ee2d0_idx',
            old_name='inv_var_inv_var_idx',
        ),
        migrations.AlterField(
            model_name='inventorylegacymapping',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylegacymapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
