# Generated by Django 4.2.9 on 2025-09-23 17:58

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0041_alter_setpricecategory_options_and_more'),
        ('inventory', '0076_inventory_pricing_to_decimal'),  # ensure this applies after 0076
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderout',
            options={},
        ),
        migrations.AlterField(
            model_name='orderout',
            name='internal_company',
            field=models.CharField(
                'Internal Company',
                max_length=32,
                choices=[
                    ('LK Design', 'LK Design'),
                    ('Krueger Printing', 'Krueger Printing'),
                    ('Office Supplies', 'Office Supplies'),
                ],
            ),
        ),

        # Constraints (if you want them):
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=~models.Q(open=True, billed=True),
                name='oo_not_both_open_and_billed',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=(models.Q(purchase_price__gte=0) | models.Q(purchase_price__isnull=True)),
                name='oo_purchase_price_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=(models.Q(percent_markup__gte=0) | models.Q(percent_markup__isnull=True)),
                name='oo_percent_markup_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=(models.Q(quantity__gte=0) | models.Q(quantity__isnull=True)),
                name='oo_quantity_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=(models.Q(unit_price__gte=0) | models.Q(unit_price__isnull=True)),
                name='oo_unit_price_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(
                check=(models.Q(total_price__gte=0) | models.Q(total_price__isnull=True)),
                name='oo_total_price_nonneg',
            ),
        ),
        migrations.AddConstraint(
            model_name='inventorymaster',
            constraint=models.CheckConstraint(
                check=models.Q(units_per_base_unit__gt=0),
                name='ipn_units_per_base_unit_gt_0',
            ),
        ),
        # NOTE: No AlterField for InventoryMaster.price_group here.
    ]