# Generated by Django 4.2.9 on 2026-02-13 16:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0045_alter_measurement_name'),
        ('inventory', '0073_rename_inv_var_inv_var_idx_inventory_i_invento_1ee2d0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryqtyvariations',
            name='is_base_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryqtyvariations',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='inventoryqtyvariations',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryqtyvariations',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.measurement'),
        ),
        migrations.AlterField(
            model_name='inventoryqtyvariations',
            name='variation_qty',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Variation Qty'),
        ),
    ]
