# Generated by Django 4.2.9 on 2026-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_inventoryqtyvariations_is_base_unit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['inventory_item'], name='inventory_i_invento_dded33_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['inventory_item', 'when'], name='inventory_i_invento_2444a3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['primary_vendor'], name='inventory_i_primary_676881_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['non_inventory'], name='inventory_i_non_inv_81a6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['active'], name='inventory_i_active_b42a79_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymaster',
            index=models.Index(fields=['primary_vendor', 'active', 'non_inventory'], name='inventory_i_primary_21eee7_idx'),
        ),
    ]
