# Generated by Django 4.2.9 on 2025-09-23 18:02
import re
from decimal import Decimal, InvalidOperation
from django.db import migrations, models

def to_decimal(val):
    if val is None:
        return None
    s = str(val).strip()
    if not s:
        return None
    s = s.replace(",", "")
    s = re.sub(r"[^0-9.\-]", "", s)
    try:
        return Decimal(s)
    except (InvalidOperation, ValueError):
        return None

def copy_str_to_decimal(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")
    qs = Inventory.objects.all().only("pk", "unit_cost", "price_per_m")
    for inv in qs.iterator(chunk_size=1000):
        uc = to_decimal(getattr(inv, "unit_cost", None))
        pm = to_decimal(getattr(inv, "price_per_m", None))
        updates = {}
        if uc is not None:
            updates["_unit_cost_dec"] = uc
        if pm is not None:
            updates["_price_per_m_dec"] = pm
        if updates:
            Inventory.objects.filter(pk=inv.pk).update(**updates)

def reverse_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0074_backfill_inventory_fk"),
    ]
    operations = [
        migrations.AddField(
            model_name="inventory",
            name="_unit_cost_dec",
            field=models.DecimalField(max_digits=15, decimal_places=4, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="_price_per_m_dec",
            field=models.DecimalField(max_digits=15, decimal_places=4, null=True, blank=True),
        ),
        migrations.RunPython(copy_str_to_decimal, reverse_noop),
        migrations.RemoveField(model_name="inventory", name="unit_cost"),
        migrations.RemoveField(model_name="inventory", name="price_per_m"),
        migrations.RenameField(model_name="inventory", old_name="_unit_cost_dec",  new_name="unit_cost"),
        migrations.RenameField(model_name="inventory", old_name="_price_per_m_dec", new_name="price_per_m"),
    ]