# Generated by Django 4.2.9 on 2026-02-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_inventoryledger_inventory_i_invento_dded33_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryledger',
            name='source_type',
            field=models.CharField(choices=[('AP_RECEIPT', 'AP Receipt / Invoice'), ('AP_RECEIPT_ADJUST', 'AP Receipt Adjust'), ('AP_RECEIPT_DELETE', 'AP Receipt Delete'), ('POS_SALE', 'POS Sale'), ('POS_REFUND', 'POS Refund'), ('WO_ORDEROUT', 'Workorder Item (OrderOut)'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='inventoryledger',
            index=models.Index(fields=['source_type', 'source_id'], name='inventory_i_source__cf449b_idx'),
        ),
    ]
