# Generated by Django 4.2.9 on 2025-09-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_orderout_options_and_more'),
        ('inventory', '0076_inventory_pricing_to_decimal'),
    ]

    operations = [
    ]
