# Generated by Django 4.2.9 on 2025-09-23 21:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0079_alter_orderout_options_and_more"),
    ]

    operations = []