# Generated by Django 4.2.9 on 2025-09-23 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0081_preclean_orderout'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='inv_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymaster',
            name='im_high_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='inventory_o_billed_85f584_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='inventory_o_dateent_c58660_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='inventory_o_vendor__5cfa94_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='oo_vendor_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='oo_billed_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderout',
            name='oo_open_idx',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='internal_part_number',
        ),
        migrations.AddField(
            model_name='inventory',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price_per_m',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Price Per M'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Unit Cost'),
        ),
        migrations.RunSQL(
            sql=[
                ("UPDATE inventory_orderout SET purchase_price = NULL WHERE purchase_price < 0;", []),
                ("UPDATE inventory_orderout SET percent_markup = NULL WHERE percent_markup < 0;", []),
                ("UPDATE inventory_orderout SET quantity = NULL WHERE quantity < 0;", []),
                ("UPDATE inventory_orderout SET unit_price = NULL WHERE unit_price < 0;", []),
                ("UPDATE inventory_orderout SET total_price = NULL WHERE total_price < 0;", []),
                ("UPDATE inventory_orderout SET open = 0 WHERE open = 1 AND billed = 1;", []),
            ],
            reverse_sql=[],
        ),
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(purchase_price__gte=0) | models.Q(purchase_price__isnull=True)),
                name="oo_purchase_price_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(percent_markup__gte=0) | models.Q(percent_markup__isnull=True)),
                name="oo_percent_markup_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(quantity__gte=0) | models.Q(quantity__isnull=True)),
                name="oo_quantity_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(unit_price__gte=0) | models.Q(unit_price__isnull=True)),
                name="oo_unit_price_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(total_price__gte=0) | models.Q(total_price__isnull=True)),
                name="oo_total_price_nonneg",
            ),
        ),
        # and for the open/billed pair:
        migrations.AddConstraint(
            model_name="orderout",
            constraint=models.CheckConstraint(
                check=~models.Q(open=True, billed=True),
                name="oo_not_both_open_and_billed",
            ),
        ),
    ]