# Generated by Django 4.2.9 on 2025-09-23 21:39

from django.db import migrations

def noop(apps, schema_editor):
    # Constraints were already removed in earlier migrations.
    # Nothing to do; keep this migration as a marker.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0082_remove_orderout_oo_not_both_open_and_billed_and_more"),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=migrations.RunPython.noop),
    ]