# Generated by Django 4.2.9 on 2025-09-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0052_workorder_delivered'),
        ('controls', '0041_alter_setpricecategory_options_and_more'),
        ("inventory", "0078_price_group_to_through"),
        ('inventory', '0084_fix_orderout_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderout',
            options={'ordering': ['-dateentered']},
        ),
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='controls.groupcategory'),
        ),
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['billed'], name='inventory_o_billed_85f584_idx'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['dateentered'], name='inventory_o_dateent_c58660_idx'),
        ),
        migrations.AddIndex(
            model_name='orderout',
            index=models.Index(fields=['vendor', 'dateentered'], name='inventory_o_vendor__5cfa94_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('open', True), ('billed', True), _negated=True), name='oo_not_both_open_and_billed'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0), ('purchase_price__isnull', True), _connector='OR'), name='oo_purchase_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('percent_markup__gte', 0), ('percent_markup__isnull', True), _connector='OR'), name='oo_percent_markup_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0), ('quantity__isnull', True), _connector='OR'), name='oo_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0), ('unit_price__isnull', True), _connector='OR'), name='oo_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0), ('total_price__isnull', True), _connector='OR'), name='oo_total_price_nonneg'),
        ),
    ]
