# Generated by Django 4.2.9 on 2025-10-03 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # IMPORTANT: keep this pointing at the migration that already added
        # internal_part_number / is_active / merged_into to InventoryMaster.
        ('inventory', '0087_inventoryitem_inventorymergelog_pricehistory_and_more'),
    ]

    operations = [
        # New simple item used by pricing/history/etc.
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('merged_into', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='merged_children',
                    to='inventory.inventoryitem',
                )),
            ],
        ),

        migrations.CreateModel(
            name='InventoryMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('merged_ids', models.JSONField()),
                ('details', models.JSONField(default=dict)),
                ('previous_names', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('target', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='+',
                    to='inventory.inventoryitem',
                )),
                ('user', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),

        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(db_index=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='price_history',
                    to='inventory.inventoryitem',
                )),
                ('vendor', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='inventory.vendor',
                )),
            ],
        ),

        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='purchase_lines',
                    to='inventory.inventoryitem',
                )),
                ('vendor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='inventory.vendor',
                )),
            ],
        ),

        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(blank=True, max_length=128, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vendor_items',
                    to='inventory.inventoryitem',
                )),
                ('vendor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='vendor_items',
                    to='inventory.vendor',
                )),
            ],
        ),

        migrations.CreateModel(
            name='WorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventory_item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='wo_items',
                    to='inventory.inventoryitem',
                )),
            ],
        ),

        # --- Alterations that do NOT add duplicate columns on InventoryMaster ---

        migrations.AlterField(
            model_name='inventory',
            name='master',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inventories',
                to='inventory.inventorymaster',
            ),
        ),

        migrations.AlterField(
            model_name='inventorymaster',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),

        migrations.AlterField(
            model_name='inventorymaster',
            name='primary_vendor',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='inventory.vendor',
            ),
        ),

        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),

        migrations.SeparateDatabaseAndState(
        state_operations=[
            migrations.AddIndex(
                model_name='inventorypricinggroup',
                index=models.Index(
                    fields=['inventory'],
                    name='inventory_i_invento_f914b4_idx',
                ),
            ),
        ],
        database_operations=[
            migrations.RunSQL(
                sql=(
                    'CREATE INDEX IF NOT EXISTS "inventory_i_invento_f914b4_idx" '
                    'ON "inventory_inventorypricinggroup" ("inventory_id")'
                ),
                reverse_sql=(
                    'DROP INDEX IF EXISTS "inventory_i_invento_f914b4_idx"'
                ),
            ),
        ],
    ),

        migrations.AlterUniqueTogether(
            name='vendoritem',
            unique_together={('vendor', 'item')},
        ),
    ]