# Generated by Django 4.2.9 on 2025-10-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0090_inventoryitem_inventorymaster_internal_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderout',
            name='billed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Billed'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='open',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
