# Generated by Django 4.2.9 on 2025-10-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0091_alter_orderout_billed_alter_orderout_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymergelog',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_items', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wo_items', to='inventory.inventorymaster'),
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
