# Generated by Django 4.2.9 on 2025-10-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0092_alter_inventorymergelog_target_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkorderItem',
        ),
    ]
