# Generated by Django 4.2.9 on 2025-10-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0094_rename_inventory_master_to_internal_part_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemPricingGroup',
        ),
        migrations.RemoveConstraint(
            model_name='orderout',
            name='oo_purchase_price_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orderout',
            name='oo_percent_markup_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orderout',
            name='oo_quantity_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orderout',
            name='oo_unit_price_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='orderout',
            name='oo_total_price_nonneg',
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='units_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Units per base unit'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_item_links', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_item_links', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='internal_part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='inventory.inventorymaster'),
        ),
    ]
