# Generated by Django 4.2.9 on 2025-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0095_delete_itempricinggroup_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0), ('purchase_price__isnull', True), _connector='OR'), name='oo_purchase_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('percent_markup__gte', 0), ('percent_markup__isnull', True), _connector='OR'), name='oo_percent_markup_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0), ('quantity__isnull', True), _connector='OR'), name='oo_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gte', 0), ('unit_price__isnull', True), _connector='OR'), name='oo_unit_price_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderout',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0), ('total_price__isnull', True), _connector='OR'), name='oo_total_price_nonneg'),
        ),
    ]
