# Generated by Django 4.2.9 on 2025-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0096_orderout_oo_purchase_price_nonneg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPricingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
    ]
