# Generated by Django 4.2.9 on 2025-10-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0097_itempricinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_group_links', to='inventory.inventorymaster'),
        ),
    ]
