# Generated by Django 4.2.9 on 2025-10-23 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0043_alter_groupcategory_name_grouplink'),
        ('inventory', '0098_alter_inventorypricinggroup_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='controls.groupcategory'),
        ),
    ]
