# Generated by Django 4.2.9 on 2025-10-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0043_alter_groupcategory_name_grouplink'),
        ('inventory', '0099_alter_inventorypricinggroup_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorymaster',
            name='ipn_units_per_base_unit_gt_0',
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='price_per_m',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Price Per M'),
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='controls.groupcategory'),
        ),
        migrations.AddConstraint(
            model_name='inventorymaster',
            constraint=models.CheckConstraint(check=models.Q(('units_per_base_unit__isnull', True), ('units_per_base_unit__gt', 0), _connector='OR'), name='ipn_units_per_base_unit_gt_0_or_null'),
        ),
    ]
