"""
Django settings for studio_management project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path
import sentry_sdk

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "file": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": "/home/adam/logs/debug.log",
#         },
#     },
#     "loggers": {
#         "django": {
#             "handlers": ["file"],
#             "level": "WARNING",
#             "propagate": True,
#         },
#     },
# }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Allow SSL Change if domain name changes
CSRF_TRUSTED_ORIGINS = ["https://staging.lkdesignstudios.com", "http://staging.lkdesignstudios.com", 
                        "https://studiomanagement.lkdesignstudios.com", "http://studiomanagement.lkdesignstudios.com"]
#CSRF_TRUSTED_ORIGINS = []

# --- Environment gates ---
RUNNING_TESTS = "pytest" in sys.modules or bool(os.environ.get("PYTEST_CURRENT_TEST"))
DJANGO_ENV = os.environ.get("DJANGO_ENV", "development").lower()  # "production" or "development"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-x8b(_)4hn$na81seyn%ffeu=ngkw1+tb3d7-hlrhl1^adk4#ex')
#print(SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get('DEBUG')) == "1"


ALLOWED_HOSTS = ['localhost', '10.6.83.220', '10.6.83.230', 'studiomanagement.lkdesignstudios.com', '10.6.83.229', 'staging.lkdesignstudios.com']
#ALLOWED_HOSTS += os.environ.get('ALLOWED_HOST').split(',')
# if not DEBUG:
#     ALLOWED_HOSTS += os.environ.get('ALLOWED_HOST').split(',')
# else:
#     ALLOWED_HOSTS += ['localhost', '10.6.83.220']



#print(ALLOWED_HOSTS)


# Application definition

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'localflavor',
    'django_htmx',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'rest_framework',
    'django_crontab',
    'django_filters',

]

LOCAL_APPS = [
    
    'accounts',
    'controls',
    'customers',
    'dashboard',
    'devtools',
    'inventory',
    'finance',
    'krueger',
    'onlinestore',
    'pdf',
    'pricesheet',
    'printleader',
    'retail',
    #'vendors',
    'workorders',
    
]

INSTALLED_APPS = DEFAULT_APPS + LOCAL_APPS + THIRD_PARTY_APPS

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'studio_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates",],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studio_management.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# IS_TESTS = os.environ.get("PYTEST_CURRENT_TEST") or "pytest" in sys.modules
# TESTING = (str(os.environ.get("TESTING")) == "1") or bool(IS_TESTS)

# if not TESTING:
#     #Production database
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'OPTIONS': {
#         	        'read_default_file': '/etc/mysql/my.cnf',
#     	},
#         }
#     }
# else:
#     #Development database
# #     DATABASES = {
# #         "default": {
# #             "ENGINE": os.environ.get('ENGINE'),
# #             "NAME": BASE_DIR / os.environ.get("MYSQL_DATABASE", "studio"),      # non-empty!
# #             "OPTIONS": {"read_default_file": "/etc/mysql/my.cnf"},
# #             "TEST": {"NAME": os.environ.get("MYSQL_TEST_DATABASE", "studio_test")},
# #     }
# # }
#     #Development Database
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": BASE_DIR / "test.sqlite3",
#         }
#     }
#     # #Development database
#     # DATABASES = {
#     #     'default': {
#     #         'ENGINE': os.environ.get('ENGINE'),
#     #         'NAME': BASE_DIR / os.environ.get('NAME'),
#     #     }
#     # }

# if not TESTING:
#     #Production Sentry
#     sentry_sdk.init(
#         dsn="https://8180ad13bf40e37b2df3bb08cfa3ecfa@o4507963680096256.ingest.us.sentry.io/4507963733180416",
#         # Set traces_sample_rate to 1.0 to capture 100%
#         # of transactions for tracing.
#         traces_sample_rate=1.0,
#         # Set profiles_sample_rate to 1.0 to profile 100%
#         # of sampled transactions.
#         # We recommend adjusting this value in production.
#         profiles_sample_rate=1.0,
#     )
# else:
#     #Development Sentry
#     sentry_sdk.init(
#     #Uncomment next line to allow for Sentry data
#     #dsn="https://86f2807741dc55ed2fd9182d9471e38d@o4507963680096256.ingest.us.sentry.io/4507963682324480",
#         # Set traces_sample_rate to 1.0 to capture 100%
#         # of transactions for tracing.
#         traces_sample_rate=1.0,
#         # Set profiles_sample_rate to 1.0 to profile 100%
#         # of sampled transactions.
#         # We recommend adjusting this value in production.
#         profiles_sample_rate=1.0,
#     )



# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # DATABASES = {
# #     'default': {
# #         'ENGINE': os.environ.get('ENGINE'),
# #         'NAME': BASE_DIR / os.environ.get('NAME'),
# #         'USER': os.environ.get('USER'),
# #         'PASSWORD': os.environ.get('HOST'),
# #         'HOST': os.environ.get('HOST'),
# #         'PORT': os.environ.get('PORT'),
# #     }
# # }

# # DATABASES = {
# #     'default' : os.environ.get('DB')
# # }

# --- Detect "real" test runs only -------------------------------------------
def _running_tests() -> bool:
    # True when `manage.py test` (Django) or pytest is actually executing.
    return ("test" in sys.argv) or (os.environ.get("PYTEST_CURRENT_TEST") is not None)

TESTING = _running_tests()
# ---------------------------------------------------------------------------

# --- Databases ---
if DJANGO_ENV == "production" and not RUNNING_TESTS:
    # Production MySQL (uses credentials in /etc/mysql/my.cnf)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "OPTIONS": {"read_default_file": "/etc/mysql/my.cnf"},
        }
    }
else:
    # Local dev & tests: SQLite (tests get a separate file automatically)
    SQLITE_NAME = BASE_DIR / ("test.sqlite3" if RUNNING_TESTS else "db.sqlite3")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_NAME,
        }
    }

# --- Sentry ---
if DJANGO_ENV == "production" and not RUNNING_TESTS:
    sentry_sdk.init(
        dsn="https://8180ad13bf40e37b2df3bb08cfa3ecfa@o4507963680096256.ingest.us.sentry.io/4507963733180416",
        traces_sample_rate=1.0,
        profiles_sample_rate=1.0,
    )
else:
    sentry_sdk.init(
        # dsn="...optional dev DSN...",
        traces_sample_rate=1.0,
        profiles_sample_rate=1.0,
    )


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Auth redirects
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "dashboard:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

#USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/') 


# STATICFILES_DIRS = [
#     #BASE_DIR / "static",
#     BASE_DIR / "templates/static",
# ]

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures'),
)

# Media Files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRONJOBS = [
    ('*/5 * * * *', 'finance.cron.ar_aging'),
    ('*/5 * * * *', 'finance.cron.krueger_ar_aging')
]

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}