# Generated by Django 4.2.9 on 2024-07-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintleaderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printleader_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader Invoice')),
                ('customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer')),
                ('printleader_customer_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader Customer Number')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('nontaxable_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Non taxable amount')),
                ('taxable_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxable Amount')),
                ('tax_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax')),
                ('invoice_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Total')),
            ],
        ),
    ]
