# Generated by Django 4.2.9 on 2024-07-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printleader', '0003_alter_printleadersoritl_workmess'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintleaderHighLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printleader_invoice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader Invoice')),
                ('customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer')),
                ('printleader_customer_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader Customer Number')),
                ('printleader_job_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader Job Name')),
            ],
        ),
    ]
