# Generated by Django 4.2.9 on 2024-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printleader', '0004_rename_yourmodelname_printleadersoordedt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintleaderSORITL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice')),
                ('Done', models.CharField(blank=True, max_length=200, null=True, verbose_name='Done')),
                ('Item', models.CharField(blank=True, max_length=200, null=True, verbose_name='Item')),
                ('E_deptn', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_deptn')),
                ('E_yn', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_yn')),
                ('E_field', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_field')),
                ('E_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_desc')),
                ('E_um', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_um')),
                ('E_units', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_units')),
                ('E_amt', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_amt')),
                ('E_setup', models.CharField(blank=True, max_length=200, null=True, verbose_name='E_setup')),
                ('Unitshr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unitshr')),
                ('Stime', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stime')),
                ('Ptime', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ptime')),
                ('Dact_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dact_time')),
                ('Itemtotal', models.CharField(blank=True, max_length=200, null=True, verbose_name='Itemtotal')),
                ('Unitcost', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unitcost')),
                ('Workmess', models.CharField(blank=True, max_length=200, null=True, verbose_name='Workmess')),
                ('Barcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Barcode')),
                ('Taxitem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxitem')),
                ('Taxperc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxperc')),
                ('Bhc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bhc')),
                ('Costcent', models.CharField(blank=True, max_length=200, null=True, verbose_name='Costcent')),
                ('Emp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emp')),
                ('Schedule', models.CharField(blank=True, max_length=200, null=True, verbose_name='Schedule')),
                ('Prodhrs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prodhrs')),
                ('Ordersort', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ordersort')),
                ('Orditem', models.CharField(blank=True, max_length=200, null=True, verbose_name='Orditem')),
                ('Type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Type')),
                ('Accessed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accessed')),
                ('Action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Action')),
                ('Keyid', models.CharField(blank=True, max_length=200, null=True, verbose_name='Keyid')),
                ('Sortdone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sortdone')),
            ],
        ),
    ]
