# Generated by Django 4.2.9 on 2024-01-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_category_modal'),
        ('krueger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='jobnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobnumber', to='workorders.workorder'),
        ),
    ]
