# Generated by Django 4.2.9 on 2024-01-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0003_alter_kruegerjobdetail_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kruegerjobdetail',
            name='jobquote',
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='hr_customer',
            field=models.CharField(default='1', max_length=100, verbose_name='Customer Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
    ]
