# Generated by Django 4.2.9 on 2024-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0004_remove_kruegerjobdetail_jobquote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kruegerjobdetail',
            old_name='jobnumber',
            new_name='workorder',
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='hr_workorder',
            field=models.CharField(default='1', max_length=100, verbose_name='Workorder'),
            preserve_default=False,
        ),
    ]
