# Generated by Django 4.2.9 on 2024-03-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventorydetail_item_and_more'),
        ('workorders', '0018_alter_workorder_customer_and_more'),
        ('krueger', '0004_wideformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='paper_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder'),
        ),
        migrations.AlterField(
            model_name='wideformat',
            name='workorder',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder'),
        ),
    ]
