# Generated by Django 4.2.9 on 2024-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0005_alter_kruegerjobdetail_packaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='override_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Override Price'),
        ),
        migrations.AddField(
            model_name='wideformat',
            name='override_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Override Price'),
        ),
    ]
