# Generated by Django 4.2.9 on 2024-01-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0007_kruegerjobdetail_workorder_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='billed',
            field=models.BooleanField(default=False, verbose_name='Billed'),
        ),
    ]
