# Generated by Django 4.2.9 on 2024-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0008_rename_set_per_book_kruegerjobdetail_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='bulkmail_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bulkmail Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='drill_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Drill Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='fold_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fold Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='mailmerge_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mailmerge Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc1_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Misc1 Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc2_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Misc2 Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc3_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Misc3 Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='misc4_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Misc4 Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='numbering_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numbering Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='pad_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padding Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='perf_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Perf Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='staple_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Staple Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='tab_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tab Note'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='wraparound_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wraparound Note'),
        ),
    ]
