# Generated by Django 4.2.9 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0009_kruegerjobdetail_bulkmail_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='wideformat',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
    ]
