# Generated by Django 4.2.9 on 2024-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0010_alter_kruegerjobdetail_hr_workorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='workorder',
            field=models.CharField(default='1', max_length=100, verbose_name='Workorder ID'),
            preserve_default=False,
        ),
    ]
