# Generated by Django 4.2.9 on 2024-07-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0010_alter_kruegerjobdetail_internal_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='step_duplo_price',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Cost for duplo'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='step_duplo_tasks',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Number of tasks'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='step_run_through_duplo',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Run through Duplo'),
        ),
    ]
