# Generated by Django 4.2.9 on 2024-07-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0011_kruegerjobdetail_step_duplo_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='duplo_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duplo Note'),
        ),
    ]
