# Generated by Django 4.2.9 on 2024-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0012_kruegerjobdetail_duplo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='step_duplo_price_per_task',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Number of tasks'),
        ),
    ]
