# Generated by Django 4.2.9 on 2024-07-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0013_kruegerjobdetail_step_duplo_price_per_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='duplo_number_of_pieces',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Number of pieces'),
        ),
    ]
