# Generated by Django 4.2.9 on 2024-01-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0013_kruegerjobdetail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='last_item_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order'),
        ),
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='last_item_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price'),
        ),
    ]
