# Generated by Django 4.2.9 on 2024-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0014_kruegerjobdetail_duplo_number_of_pieces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='step_duplo_price_per_task',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Price per task'),
        ),
    ]
