# Generated by Django 4.2.9 on 2024-02-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0015_alter_kruegerjobdetail_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='press_sheet_per_parent',
            field=models.PositiveBigIntegerField(blank=True, max_length=100, null=True, verbose_name='Press sheets / Parent'),
        ),
    ]
