# Generated by Django 4.2.9 on 2024-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0016_alter_kruegerjobdetail_press_sheet_per_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='press_sheet_per_parent',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Press sheets / Parent'),
        ),
    ]
