# Generated by Django 4.2.9 on 2024-02-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0017_alter_kruegerjobdetail_press_sheet_per_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='kruegerjobdetail',
            name='side_1_inktype',
            field=models.CharField(choices=[('B/W', 'B_W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid_plus')], default='None', max_length=100, verbose_name='Side 1 Ink'),
            preserve_default=False,
        ),
    ]
