# Generated by Django 4.2.9 on 2024-02-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krueger', '0019_kruegerjobdetail_side_2_inktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='side_1_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, verbose_name='Side 1 Ink'),
        ),
        migrations.AlterField(
            model_name='kruegerjobdetail',
            name='side_2_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, verbose_name='Side 1 Ink'),
        ),
    ]
