# Generated by Django 4.2.9 on 2024-01-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
    ]
