# Generated by Django 4.2.9 on 2024-02-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_setprice_category'),
        ('pricesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesheet',
            name='paper_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
