# Generated by Django 4.2.9 on 2024-01-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0018_category_formname'),
        ('pricesheet', '0003_remove_pricesheet_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.category'),
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.subcategory'),
        ),
    ]
