# Generated by Django 4.2.9 on 2024-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0004_pricesheet_category_pricesheet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesheet',
            name='name',
            field=models.CharField(default='1', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
