# Generated by Django 4.2.9 on 2024-03-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0012_category_wideformat'),
        ('pricesheet', '0005_wideformatpricesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='billed',
        ),
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='dateentered',
        ),
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='last_item_order',
        ),
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='last_item_price',
        ),
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='workorder_item',
        ),
        migrations.AlterField(
            model_name='wideformatpricesheet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.category'),
        ),
        migrations.AlterField(
            model_name='wideformatpricesheet',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.subcategory'),
        ),
    ]
