# Generated by Django 4.2.9 on 2024-02-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0006_fixedcosts_alter_pricesheet_press_sheet_per_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedCosts',
            new_name='FixedCost',
        ),
    ]
