# Generated by Django 4.2.9 on 2024-02-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0008_alter_fixedcost_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
    ]
