# Generated by Django 4.2.9 on 2024-03-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventory_length_measurement_and_more'),
        ('pricesheet', '0009_wideformatpricesheet_paper_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wideformatpricesheet',
            name='paper_stock',
        ),
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='laminate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wf_laminate', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wf_mask', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wf_material', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='substrate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wf_substrate', to='inventory.inventory'),
        ),
    ]
