# Generated by Django 4.2.9 on 2024-02-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0009_pricesheet_edited_alter_pricesheet_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedCost',
        ),
    ]
