# Generated by Django 4.2.9 on 2024-03-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0010_remove_wideformatpricesheet_paper_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='override_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Override Price'),
        ),
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='override_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Override Price'),
        ),
    ]
