# Generated by Django 4.2.9 on 2024-02-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0010_delete_fixedcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='side_1_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], default='None', max_length=100, verbose_name='Side 1 Ink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricesheet',
            name='side_2_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], default='None', max_length=100, verbose_name='Side 1 Ink'),
            preserve_default=False,
        ),
    ]
