# Generated by Django 4.2.9 on 2024-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0011_pricesheet_override_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesheet',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], default='Krueger Printing', max_length=100, verbose_name='Internal Company'),
            preserve_default=False,
        ),
    ]
