# Generated by Django 4.2.9 on 2024-02-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_category_subcategory'),
        ('pricesheet', '0012_alter_pricesheet_paper_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesheet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.category'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.subcategory'),
        ),
    ]
