# Generated by Django 4.2.9 on 2024-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0012_pricesheet_internal_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesheet',
            name='side_2_inktype',
            field=models.CharField(choices=[('B/W', 'B/W'), ('Color', 'Color'), ('None', 'None'), ('Vivid', 'Vivid'), ('Vivid Plus', 'Vivid Plus')], max_length=100, verbose_name='Side 2 Ink'),
        ),
        migrations.AlterField(
            model_name='pricesheet',
            name='step_print_cost_side_2_price',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Printing Cost Side 2'),
        ),
    ]
