# Generated by Django 4.2.9 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0014_rename_set_per_book_pricesheet_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesheet',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='wideformatpricesheet',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
    ]
