# Generated by Django 4.2.9 on 2025-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0015_alter_pricesheet_internal_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wideformatpricesheet',
            name='single_double_sided',
            field=models.IntegerField(blank=True, choices=[(1, 'Single Sided'), (2, 'Double Sided')], default=1, null=True),
        ),
    ]
