# Generated by Django 4.2.9 on 2025-09-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesheet', '0016_wideformatpricesheet_single_double_sided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wideformatpricesheet',
            name='single_double_sided',
            field=models.IntegerField(choices=[(1, 'Single Sided'), (2, 'Double Sided')], default=1, null=True),
        ),
    ]
