# Generated by Django 4.2.9 on 2024-09-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0036_rename_groupcategory_GroupCategory'),
        ('inventory', '0056_alter_inventorymaster_price_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymaster',
            name='pricing_group',
        ),
        migrations.AlterField(
            model_name='inventorypricinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.GroupCategory'),
        ),
    ]
