# Generated by Django 4.2.9 on 2024-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_vendor_inventory_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='non_inventory_vendor',
            field=models.BooleanField(default=True, verbose_name='Non Inventory Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='inventory_vendor',
            field=models.BooleanField(default=True, verbose_name='Inventory Vendor'),
        ),
    ]
