# Generated by Django 4.2.9 on 2024-09-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0059_vendor_non_inventory_vendor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='inventorymaster',
            name='non_inventory',
            field=models.BooleanField(verbose_name='Non Inventory Item'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='non_inventory',
            field=models.BooleanField(verbose_name='Non Inventory Item'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='retail',
            field=models.BooleanField(verbose_name='Retail Item'),
        ),
        migrations.AlterField(
            model_name='vendoritemdetail',
            name='supplies',
            field=models.BooleanField(verbose_name='Supply Item'),
        ),
    ]
