# Generated by Django 4.2.9 on 2024-02-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Website')),
                ('po_number', models.CharField(blank=True, max_length=100, verbose_name='PO Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('customer_number', models.CharField(blank=True, max_length=100, verbose_name='Customer Number')),
                ('tax_exempt', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Tax Exempt')),
                ('tax_exempt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID Number')),
                ('tax_exempt_paperwork', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
    ]
