# Generated by Django 4.2.9 on 2024-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes:'),
        ),
    ]
