# Generated by Django 4.2.9 on 2024-01-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_alter_workorder_contact_alter_workorder_customer'),
        ('customers', '0002_contact_remove_customercontact_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerContact',
        ),
        migrations.AddField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer'),
        ),
    ]
