# Generated by Django 4.2.9 on 2024-01-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_customercontact_contact_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer'),
            preserve_default=False,
        ),
    ]
