# Generated by Django 4.2.9 on 2024-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_contact_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
