# Generated by Django 4.2.9 on 2024-01-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_contact_address1_alter_contact_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='po_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='PO Number'),
        ),
    ]
