# Generated by Django 4.2.9 on 2024-03-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_contact_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_exempt_paperwork',
            field=models.ImageField(blank=True, null=True, upload_to='tax_exempt_form/'),
        ),
    ]
