# Generated by Django 4.2.9 on 2024-01-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
