# Generated by Django 4.2.9 on 2024-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_tax_exempt_paperwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avg_days_to_pay',
            field=models.CharField(blank=True, max_length=100, verbose_name='Avg Days to Pay'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='customer',
            name='high_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='High Balance'),
        ),
        migrations.AddField(
            model_name='customer',
            name='open_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Open Balance'),
        ),
    ]
