# Generated by Django 4.2.9 on 2024-06-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_avg_days_to_pay_customer_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes:')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipto', to='customers.customer')),
            ],
        ),
    ]
