# Generated by Django 4.2.9 on 2024-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_contact_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_exempt_paperwork',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
