# Generated by Django 4.2.9 on 2024-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_tax_exempt_customer_tax_exempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Customer Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_exempt',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Tax Exempt'),
        ),
    ]
