# Generated by Django 4.2.9 on 2024-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_shipto'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_workorder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
