# Generated by Django 4.2.9 on 2024-10-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_last_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Company Name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('address1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Website')),
                ('notes', models.TextField(blank=True, verbose_name='Notes:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('customer_number', models.CharField(blank=True, max_length=100, verbose_name='Customer Number')),
                ('tax_exempt', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Tax Exempt')),
                ('tax_exempt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID Number')),
            ],
        ),
    ]
