# Generated by Django 4.2.9 on 2024-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_mailingcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingcustomer',
            name='notes',
        ),
    ]
