# Generated by Django 4.2.9 on 2025-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_mail_bounced_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_exempt_paperwork',
            field=models.FileField(blank=True, null=True, upload_to='tax_exempt_form/'),
        ),
    ]
