# Generated by Django 4.2.9 on 2024-11-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitemdetails',
            old_name='internal_part_number',
            new_name='item',
        ),
    ]
