# Generated by Django 4.2.9 on 2024-11-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_rename_internal_part_number_storeitemdetails_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=100, verbose_name='Name')),
                ('var_qty', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Variation Qty')),
                ('var_online_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Online Store Price')),
                ('var_multiplier', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Multiplier from Base Unit')),
                ('var_markup', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Markup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinestore.storeitemdetails')),
            ],
        ),
    ]
