# Generated by Django 4.2.9 on 2024-12-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_vendoritemdetail_vendor'),
        ('onlinestore', '0004_storeitemdetails_retail_store_price_storeitempricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItemDetailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Unit Cost')),
                ('online_store_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Online Store Price')),
                ('retail_store_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Retail Store Price')),
                ('oneforty_percent', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='140 Percent Markup')),
                ('actual_markup', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True, verbose_name='Actual Markup')),
                ('date_last_price_change', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymaster')),
            ],
        ),
    ]
