# Generated by Django 4.2.9 on 2025-02-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_storeitemdetailhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitemdetailhistory',
            name='actual_markup',
        ),
        migrations.RemoveField(
            model_name='storeitemdetailhistory',
            name='high_cost',
        ),
        migrations.RemoveField(
            model_name='storeitemdetailhistory',
            name='oneforty_percent',
        ),
    ]
