# Generated by Django 4.2.9 on 2024-08-18 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0033_vendor_retail_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailInventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('primary_vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Vendor Part Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='High Price')),
                ('primary_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailVendorItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='High Price')),
                ('internal_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Invoice Number')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total')),
                ('date_due', models.DateField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount')),
                ('discount_date_due', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False, null=True, verbose_name='Paid')),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('Trade', 'Trade'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Payment Method')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Unit Cost')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Qty')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('internal_part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinvoices')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vendor')),
            ],
        ),
    ]
