# Generated by Django 4.2.9 on 2024-08-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailinventorymaster',
            name='primary_vendor',
        ),
    ]
