# Generated by Django 4.2.9 on 2024-08-16 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_retailinvoiceitem_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinvoices'),
        ),
        migrations.RemoveField(
            model_name='retailvendoritemdetail',
            name='internal_part_number',
        ),
        migrations.AddField(
            model_name='retailvendoritemdetail',
            name='internal_part_number',
            field=models.ManyToManyField(to='retail.retailinventorymaster'),
        ),
    ]
