# Generated by Django 4.2.9 on 2024-08-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_invoiceitem'),
        ('inventory', '0036_vendoritemdetail'),
        ('retail', '0002_rename_iteminvoice_invoiceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='internal_part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Delete_IPN', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Delete_invoice', to='finance.accountspayable'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Delete_vendor', to='inventory.vendor'),
        ),
    ]
