# Generated by Django 4.2.9 on 2024-08-24 20:35

from django.db import migrations

SQL = """
DROP TABLE IF EXISTS `retail_invoiceitem`;
DROP TABLE IF EXISTS `retail_iteminvoice`;  -- old name, just in case
"""

class Migration(migrations.Migration):
    dependencies = [
        ("retail", "0003_delete_testtable_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name="InvoiceItem")],
            database_operations=[migrations.RunSQL(sql=SQL, reverse_sql=migrations.RunSQL.noop)],
        )
    ]