# Generated by Django 4.2.9 on 2024-08-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_delete_inventorymaster'),
        ('finance', '0016_alter_accountspayable_invoice_number'),
        ('retail', '0003_retailinventorymaster_primary_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.accountspayable'),
        ),
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='retailvendoritemdetail',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='High Price'),
        ),
        migrations.CreateModel(
            name='InventoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('unit_cost', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current_stock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock')),
                ('retail_inventory_part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinventorymaster')),
                ('supplies_internal_part_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory')),
            ],
        ),
    ]
