# Generated by Django 4.2.9 on 2024-08-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_alter_retailinvoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetailInvoices',
        ),
    ]
