# Generated by Django 4.2.9 on 2025-11-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('retail', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_sales', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], default='Office Supplies', max_length=100),
        ),
    ]
