# Generated by Django 4.2.9 on 2025-11-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0052_workorder_delivered'),
        ('retail', '0006_retailsale_customer_retailsale_internal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_sales', to='workorders.workorder'),
        ),
    ]
