# Generated by Django 4.2.9 on 2025-11-21 20:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_retailsale_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='If true, no tax will be charged on this sale.', verbose_name='Tax Exempt'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.055'), help_text='Tax rate as a decimal (e.g. 0.055 for 5.5%)', max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='retailsale',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
