# Generated by Django 4.2.9 on 2025-11-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('retail', '0008_retailsale_tax_exempt_retailsale_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailCashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, default='Cash', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Usually the Walk-in / Cash Sale customer record.', null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_record', to='retail.retailsale')),
            ],
        ),
    ]
