# Generated by Django 4.2.9 on 2025-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0009_retailcashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcashsale',
            name='payment_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
