# Generated by Django 4.2.9 on 2025-11-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_retailcashsale_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='locked',
            field=models.BooleanField(default=False, help_text='When true, POS lines and customer should not be edited.'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='original_sale',
            field=models.ForeignKey(blank=True, help_text='If set, this sale is a refund/adjustment of the original sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='retail.retailsale'),
        ),
        migrations.AddField(
            model_name='retailsale',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When this sale was fully paid (POS).', null=True),
        ),
    ]
