# Generated by Django 4.2.9 on 2025-11-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0011_retailsale_locked_retailsale_original_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
