# Generated by Django 4.2.9 on 2025-12-01 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_inventoryretailprice'),
        ('retail', '0012_retailsale_is_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsaleline',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retail_lines', to='inventory.inventorymaster'),
        ),
    ]
