# Generated by Django 4.2.9 on 2025-12-04 19:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_inventoryledger'),
        ('retail', '0013_alter_retailsaleline_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsaleline',
            name='sold_variation',
            field=models.ForeignKey(blank=True, help_text='If set, qty represents this variation; base units = qty * sold_variation.variation_qty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_sale_lines', to='inventory.inventoryqtyvariations'),
        ),
        migrations.AlterField(
            model_name='retailsale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.055'), help_text='Tax rate as a decimal (e.g. 0.055 for 5.5%).', max_digits=5, verbose_name='Tax Rate'),
        ),
    ]
