# Generated by Django 4.2.9 on 2025-12-04 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_tax_exempt_paperwork'),
        ('retail', '0014_retailsaleline_sold_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='requires_delivery',
            field=models.BooleanField(default=False, help_text='If true, this sale should be included on the delivery list.'),
        ),
        migrations.CreateModel(
            name='DeliveryRouteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route_entry', to='customers.customer')),
            ],
            options={
                'ordering': ['sort_order', 'customer__company_name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='customers.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='retail.retailsale')),
            ],
        ),
    ]
