# Generated by Django 4.2.9 on 2025-12-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0055_remove_workorderitem_delivery_date_and_more'),
        ('retail', '0015_retailsale_requires_delivery_deliveryrouteentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='workorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='workorders.workorder'),
        ),
    ]
