# Generated by Django 4.2.9 on 2025-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0016_delivery_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
