# Generated by Django 4.2.9 on 2025-12-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_delivery_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='retail.retailsale'),
        ),
    ]
