# Generated by Django 4.2.9 on 2026-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0018_alter_delivery_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsaleline',
            name='is_gift_certificate',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
