# Generated by Django 4.2.9 on 2026-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0020_pos_qty_precision_and_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailsalelineaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
