# Generated by Django 4.2.9 on 2024-08-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0033_delete_printleaderhistory'),
        ('retail', '0003_officesupplies_retailinventory_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adddress 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zipcode')),
                ('phone1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone 2')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('supplier', models.BooleanField(default=True, verbose_name='Supplier')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='retailinventory',
            name='office_supply_item',
        ),
        migrations.RemoveField(
            model_name='retailinventory',
            name='paper_item',
        ),
        migrations.RemoveField(
            model_name='retailinventory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='retailinventory',
            name='qty_on_hand',
        ),
        migrations.AddField(
            model_name='retailinventory',
            name='current_stock',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Stock'),
        ),
        migrations.AddField(
            model_name='retailinventory',
            name='internal_part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Part Number'),
        ),
        migrations.AddField(
            model_name='retailinventory',
            name='retail_item',
            field=models.BooleanField(default=True, verbose_name='Retail Item'),
        ),
        migrations.AddField(
            model_name='retailinventory',
            name='unit_cost',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unit Cost'),
        ),
        migrations.AlterField(
            model_name='retailinventory',
            name='name',
            field=models.CharField(default='x', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RetailPurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('vendor_item_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('shipped_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('internal_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty')),
                ('price_per_m', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paper Stock Price per M')),
                ('total_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Price')),
                ('internal_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controls.measurement')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailinventory')),
                ('shipped_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_shipped_uom', to='controls.measurement')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
        migrations.CreateModel(
            name='RetailInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('name2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Additional Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('qty_on_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qty on Hand')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inventory_category', models.ManyToManyField(to='controls.retailinventorycategory')),
                ('office_supply_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.officesupplies')),
                ('paper_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retail.retailinventory')),
            ],
        ),
    ]
