# Generated by Django 4.2.9 on 2024-08-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_retailvendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Total')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
    ]
