# Generated by Django 4.2.9 on 2024-08-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_retailinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinvoices',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='discount_date_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='paid',
            field=models.BooleanField(default=False, null=True, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='retailinvoices',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Credit Card', 'Credit Card'), ('Trade', 'Trade'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Payment Method'),
        ),
    ]
