# Generated by Django 4.2.9 on 2024-08-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_retailinvoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='vendor_part_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number'),
        ),
        migrations.CreateModel(
            name='RetailItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('vendor_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor Part Number')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('internal_part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internal Part Number')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('high_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='High Price')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retail.retailvendor')),
            ],
        ),
    ]
