# Generated by Django 4.2.9 on 2024-08-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0009_retailinventorymaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoiceitem',
            name='internal_part_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retail.retailinventorymaster'),
            preserve_default=False,
        ),
    ]
