# Generated by Django 4.2.9 on 2024-08-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0015_retailinventorymaster_primary_vendor_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailinvoices',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Invoice Number'),
            preserve_default=False,
        ),
    ]
