# Generated by Django 4.2.9 on 2024-08-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0017_remove_retailinvoiceitem_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailinvoiceitem',
            old_name='hr_name',
            new_name='name',
        ),
    ]
