# Generated by Django 4.2.9 on 2024-02-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_customer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('hr_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name')),
                ('workorder', models.CharField(max_length=100, unique=True, verbose_name='Workorder')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='PO Number')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('quoted_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quoted Price')),
                ('original_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Order')),
                ('notes', models.TextField(blank=True, verbose_name='Notes:')),
                ('lk_workorder', models.CharField(blank=True, max_length=100, null=True, verbose_name='LK Workorder')),
                ('printleader_workorder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader')),
                ('billed', models.BooleanField(default=False, verbose_name='Billed')),
                ('tax_exempt', models.BooleanField(default=False)),
                ('percent_discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount %')),
                ('dollar_discount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Discount $')),
                ('tax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax')),
                ('subtotal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtotal')),
                ('workorder_total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Workorder Total')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_hr', models.CharField(max_length=100, verbose_name='Workorder Human Readable')),
                ('pricesheet_modified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pricesheet Modified')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('item_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Price')),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Override Price')),
                ('absolute_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Absolute Price')),
                ('last_item_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order')),
                ('last_item_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price')),
                ('notes', models.TextField(blank=True, verbose_name='Notes:')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('tax_exempt', models.BooleanField(default=False)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tax Amount')),
                ('total_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
                ('design_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.designtype')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.category')),
                ('item_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.subcategory')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
    ]
