# Generated by Django 4.2.9 on 2024-01-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder', models.CharField(max_length=100, unique=True, verbose_name='Workorder')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('quoted_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quoted Price')),
                ('original_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Order')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customercontact')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
