# Generated by Django 4.2.9 on 2024-01-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_contact_remove_customercontact_customer'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.contact'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='customers.customer'),
        ),
    ]
