# Generated by Django 4.2.9 on 2024-01-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_customercontact_contact_customer'),
        ('workorders', '0002_alter_workorder_contact_alter_workorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hr_customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='customers.customer'),
            preserve_default=False,
        ),
    ]
