# Generated by Django 4.2.9 on 2024-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorderitem_setprice_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='quote',
            field=models.BooleanField(default=False, verbose_name='Quote'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quote_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Quote Number'),
        ),
    ]
