# Generated by Django 4.2.9 on 2024-01-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_hr_customer_alter_workorder_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
            ],
        ),
    ]
