# Generated by Django 4.2.9 on 2024-02-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_quote_workorder_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='quote',
            field=models.BooleanField(choices=[('Quote', '1'), ('Workorder', '0')], default=False, verbose_name='Quote'),
        ),
    ]
