# Generated by Django 4.2.9 on 2024-01-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hr_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name'),
        ),
    ]
