# Generated by Django 4.2.9 on 2024-01-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_hr_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='lk_workorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LK Workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='printleader_workorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Printleader'),
        ),
    ]
