# Generated by Django 4.2.9 on 2024-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_alter_workorder_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='quote',
            field=models.BooleanField(choices=[('True', 'Quote'), ('False', 'Workorder')], default=False, verbose_name='Quote'),
        ),
    ]
