# Generated by Django 4.2.9 on 2024-02-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0006_alter_workorder_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='quote',
            field=models.CharField(choices=[('1', 'Quote'), ('0', 'Workorder')], max_length=100, verbose_name='Quote'),
        ),
    ]
