# Generated by Django 4.2.9 on 2024-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_alter_workorder_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='comleted',
            field=models.BooleanField(default=False),
        ),
    ]
