# Generated by Django 4.2.9 on 2024-01-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_workorder_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('design_type', models.BooleanField(blank=True, null=True, verbose_name='Design Type')),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WorkorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Price')),
                ('design_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.designtype')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorders.category')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('item_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order')),
                ('original_item_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order')),
                ('original_item_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price')),
                ('internal_company', models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], max_length=100, verbose_name='Internal Company')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.category')),
                ('workorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.workorder')),
            ],
        ),
    ]
