# Generated by Django 4.2.9 on 2024-01-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_category_designtype_workorderitem_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing')], default='LK Design', max_length=100, verbose_name='Internal Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='item_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='original_item_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Order'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='original_item_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Original Item Price'),
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
