# Generated by Django 4.2.9 on 2024-02-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0010_alter_workorder_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='billable',
            field=models.BooleanField(default=True),
        ),
    ]
