# Generated by Django 4.2.9 on 2024-02-19 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_workorderitem_billable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
