# Generated by Django 4.2.9 on 2024-01-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_workorderitem_workorder_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Modal'),
        ),
    ]
