# Generated by Django 4.2.9 on 2024-02-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_workorder_created_workorder_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='original_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Original Order'),
        ),
    ]
