# Generated by Django 4.2.9 on 2024-01-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_category_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Category'),
        ),
    ]
