# Generated by Django 4.2.9 on 2024-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_workorderitem_added_to_parent_workorderitem_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='child',
            field=models.BooleanField(default=False),
        ),
    ]
