# Generated by Django 4.2.9 on 2024-01-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0015_workorderitem_item_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='workorder_hr',
            field=models.CharField(max_length=100, verbose_name='Workorder Human Readable'),
        ),
    ]
