# Generated by Django 4.2.9 on 2024-01-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0016_alter_workorderitem_workorder_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='billed',
            field=models.BooleanField(default=False, verbose_name='Billed'),
        ),
    ]
