# Generated by Django 4.2.9 on 2024-03-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0010_postagetype'),
        ('workorders', '0016_workorder_show_notes_workorderitem_show_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='postage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.postagetype'),
        ),
    ]
