# Generated by Django 4.2.9 on 2024-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0019_subcategory_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Template'),
        ),
    ]
