# Generated by Django 4.2.9 on 2024-03-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_group_alter_profile_email_and_more'),
        ('controls', '0016_usergroup'),
        ('workorders', '0020_workorderitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='test_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.usergroup'),
        ),
    ]
