# Generated by Django 4.2.9 on 2024-02-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0021_alter_workorderitem_item_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes:'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes:'),
        ),
    ]
