# Generated by Django 4.2.9 on 2024-02-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0022_workorder_notes_workorderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
