# Generated by Django 4.2.9 on 2024-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0023_workorderitem_tax_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
