# Generated by Django 4.2.9 on 2024-03-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0026_workorder_paid_in_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='days_to_pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Days to pay'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='paid_in_full',
            field=models.BooleanField(default=False, verbose_name='Paid in Full'),
        ),
    ]
