# Generated by Django 4.2.9 on 2024-02-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0028_fixedcost_material_markup_alter_fixedcost_duplo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
