# Generated by Django 4.2.9 on 2024-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0028_workorder_aging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='aging',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aging'),
        ),
    ]
