# Generated by Django 4.2.9 on 2024-02-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0029_alter_workorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='customform',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Uses Custom Form'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='workorders.category'),
        ),
    ]
