# Generated by Django 4.2.9 on 2024-03-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0019_jobstatus_workorder_item_type_and_more'),
        ('workorders', '0029_alter_workorder_aging'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='workorder_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.jobstatus'),
        ),
    ]
