# Generated by Django 4.2.9 on 2024-03-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0030_workorder_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorders.workorder'),
        ),
    ]
