# Generated by Django 4.2.9 on 2024-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0031_alter_workorderitem_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='abandon_quote',
            field=models.BooleanField(default=False, verbose_name='Abandon Quote'),
        ),
    ]
