# Generated by Django 4.2.9 on 2024-02-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0031_workorderitem_percent_markup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Override Price'),
        ),
    ]
