# Generated by Django 4.2.9 on 2024-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0032_workorderitem_override_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='percent_markup',
        ),
        migrations.RemoveField(
            model_name='workorderitem',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='workorderitem',
            name='vendor',
        ),
    ]
