# Generated by Django 4.2.9 on 2024-03-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0032_workorder_abandon_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='show_qty_on_wo',
            field=models.BooleanField(default=True),
        ),
    ]
