# Generated by Django 4.2.9 on 2024-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0033_workorderitem_show_qty_on_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='explore_created',
            field=models.BooleanField(default=False),
        ),
    ]
