# Generated by Django 4.2.9 on 2024-02-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0033_remove_workorderitem_percent_markup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='modelname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Popup Modal'),
        ),
    ]
