# Generated by Django 4.2.9 on 2024-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0034_workorder_explore_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='void',
            field=models.BooleanField(default=False, verbose_name='Void Workorder'),
        ),
    ]
