# Generated by Django 4.2.9 on 2024-02-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0034_category_modelname_alter_category_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='setprice',
            field=models.BooleanField(default=False, null=True, verbose_name='Is setprice category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modal',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Popup Modal'),
        ),
    ]
