# Generated by Django 4.2.9 on 2024-04-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0035_workorder_void'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='void_memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Void Memo'),
        ),
    ]
