# Generated by Django 4.2.9 on 2024-02-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0035_category_setprice_alter_category_modal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Numbering',
        ),
    ]
