# Generated by Django 4.2.9 on 2024-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0036_workorder_void_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity'),
        ),
    ]
