# Generated by Django 4.2.9 on 2024-02-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_setprice_subcategory'),
        ('pricesheet', '0013_alter_pricesheet_category_and_more'),
        ('controls', '0003_category_subcategory'),
        ('workorders', '0036_delete_numbering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.category'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controls.subcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FixedCost',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
