# Generated by Django 4.2.9 on 2024-02-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_designtype'),
        ('workorders', '0037_remove_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='design_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controls.designtype'),
        ),
        migrations.DeleteModel(
            name='DesignType',
        ),
    ]
