# Generated by Django 4.2.9 on 2024-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0037_alter_workorderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='quickbooks_workorder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Krueger Office'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='internal_company',
            field=models.CharField(choices=[('LK Design', 'LK Design'), ('Krueger Printing', 'Krueger Printing'), ('Office Supplies', 'Office Supplies')], max_length=100, verbose_name='Internal Company'),
        ),
    ]
