# Generated by Django 4.2.9 on 2024-02-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0038_alter_workorderitem_design_type_delete_designtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='absolute_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Absolute Price'),
        ),
    ]
