# Generated by Django 4.2.9 on 2024-04-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0039_rename_quickbooks_workorder_workorder_kos_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='void',
            field=models.BooleanField(default=False, verbose_name='Void Workorder'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='void_memo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Void Memo'),
        ),
    ]
