# Generated by Django 4.2.9 on 2024-04-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0040_workorderitem_void_workorderitem_void_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='disount_applied',
            field=models.BooleanField(default=False, verbose_name='Void Workorder'),
        ),
    ]
