# Generated by Django 4.2.9 on 2024-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0040_workorderitem_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='total_with_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tax Amount'),
        ),
    ]
