# Generated by Django 4.2.9 on 2024-04-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0041_workorder_disount_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='disount_applied',
        ),
    ]
