# Generated by Django 4.2.9 on 2024-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0044_workorder_checked_and_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
