# Generated by Django 4.2.9 on 2024-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0045_workorder_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='orderout_waiting',
            field=models.BooleanField(default=False, verbose_name='Waiting on Orderout'),
        ),
    ]
