# Generated by Django 4.2.9 on 2025-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0049_workorder_ship_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='delivered_or_pickedup',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='delivery_pickup',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup')], default=None, max_length=100, null=True, verbose_name='Delivery or Pickup'),
        ),
    ]
