# Generated by Django 4.2.9 on 2025-09-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0050_remove_workorder_delivered_or_pickedup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='delivery_pickup',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Pickup', 'Pickup'), ('Other', 'Other')], default=None, max_length=100, null=True, verbose_name='Delivery or Pickup'),
        ),
    ]
