# Generated by Django 4.2.9 on 2025-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0051_alter_workorder_delivery_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
    ]
