# Generated by Django 4.2.9 on 2025-10-06 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_delete_workorderitem'),
        ('workorders', '0052_workorder_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wo_items', to='inventory.inventorymaster'),
        ),
    ]
