# Generated by Django 4.2.9 on 2025-11-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0052_workorder_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='retail_pos',
            field=models.BooleanField(default=False, help_text='Created from the Office Supplies retail POS screen.', verbose_name='Retail POS'),
        ),
    ]
