# Generated by Django 4.2.9 on 2025-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0053_workorder_retail_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='requires_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
