# Generated by Django 4.2.9 on 2025-10-07 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0093_delete_workorderitem'),
        ('workorders', '0053_workorderitem_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorder_items', to='inventory.inventorymaster'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=112, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='void_memo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Void Memo'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.workorder'),
        ),
    ]
