# Generated by Django 4.2.9 on 2025-12-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0054_workorderitem_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='workorderitem',
            name='requires_delivery',
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
