# Generated by Django 4.2.9 on 2025-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0055_remove_workorderitem_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date_called',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
