# Generated by Django 4.2.9 on 2025-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0056_workorder_date_called_workorder_requires_pickup'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'void', 'quote', 'completed', '-workorder'], name='wo_cust_list_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'billed', 'paid_in_full', 'date_billed'], name='wo_ar_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'completed', 'quote', 'void'], name='wo_open_idx'),
        ),
    ]
