# Generated by Django 4.2.9 on 2026-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0057_workorder_wo_cust_list_idx_workorder_wo_ar_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorderitem',
            options={'ordering': ('sort_order', 'id')},
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
