# Generated by Django 4.2.9 on 2026-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0058_alter_workorderitem_options_workorderitem_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='normalized_subtotal',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='normalized_tax',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='normalized_workorder_total',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['normalized_workorder_total'], name='wo_norm_total_idx'),
        ),
    ]
